"""locality identity by source id

Revision ID: fc986503bb00
Revises: 4eb0b2daddd9
Create Date: 2026-08-24 22:15:56.143560+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fc986503bb00'
down_revision: str | None = '4eb0b2daddd9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_locality_name'), 'localities', type_='unique')
    op.create_index('ix_locality_parent_level', 'localities', ['parent_id', 'level'], unique=False)
    op.create_unique_constraint('uq_locality_source', 'localities', ['source', 'source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_locality_source', 'localities', type_='unique')
    op.drop_index('ix_locality_parent_level', table_name='localities')
    op.create_unique_constraint(op.f('uq_locality_name'), 'localities', ['level', 'name', 'parent_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
