"""parcel geometry and facilities

Revision ID: fc40902c04da
Revises: 4470d47e599d
Create Date: 2026-08-24 18:32:59.858487+00:00
"""
from collections.abc import Sequence

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fc40902c04da'
down_revision: str | None = '4470d47e599d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('subkind', sa.String(length=60), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=40), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_facility_source')
    )
    op.create_index(op.f('ix_facilities_created_at'), 'facilities', ['created_at'], unique=False)
    op.create_index(op.f('ix_facilities_district'), 'facilities', ['district'], unique=False)
    op.create_index(op.f('ix_facilities_kind'), 'facilities', ['kind'], unique=False)
    op.create_index(op.f('ix_facilities_subkind'), 'facilities', ['subkind'], unique=False)
    op.add_column('properties', sa.Column('boundary_geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('properties', sa.Column('centre_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('properties', sa.Column('boundary_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('allow_directions', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'allow_directions')
    op.drop_column('properties', 'boundary_issues')
    op.drop_column('properties', 'centre_geom')
    op.drop_column('properties', 'boundary_geom')
    op.drop_index(op.f('ix_facilities_subkind'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_kind'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_district'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_created_at'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
