"""link submission owners to clients

Revision ID: 8a669664c408
Revises: 62ba32190706
Create Date: 2026-08-25 09:54:04.752490+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8a669664c408'
down_revision: str | None = '62ba32190706'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_submission_owners', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_seller_submission_owners_client_id'), 'seller_submission_owners', ['client_id'], unique=False)
    op.create_foreign_key(None, 'seller_submission_owners', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller_submission_owners', type_='foreignkey')
    op.drop_index(op.f('ix_seller_submission_owners_client_id'), table_name='seller_submission_owners')
    op.drop_column('seller_submission_owners', 'client_id')
    # ### end Alembic commands ###
