"""viewing fee on listings

Revision ID: 789aa1baa608
Revises: 8a669664c408
Create Date: 2026-08-25 10:39:40.736041+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '789aa1baa608'
down_revision: str | None = '8a669664c408'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('viewing_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('properties', sa.Column('visiting_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('properties', sa.Column('visiting_fee_negotiable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'visiting_fee_negotiable')
    op.drop_column('properties', 'visiting_fee')
    op.drop_column('properties', 'viewing_allowed')
    # ### end Alembic commands ###
