"""clients, commissions, investments and property commission fields

Revision ID: bde922b7f298
Revises: 29bb8246883b
Create Date: 2026-08-17 22:51:39.209764+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bde922b7f298'
down_revision: str | None = '29bb8246883b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate also proposed dropping the server defaults on
    # `construction_packages.show_price` and `properties.show_on_map`. That is
    # pre-existing model/database drift, not part of this change — removed so
    # this migration does not silently alter insert behaviour.
    op.create_table('clients',
    sa.Column('kind', sa.Enum('individual', 'company', name='client_kind'), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('national_id', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('tin', sa.String(length=64), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('contact_person', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=240), nullable=True),
    sa.Column('phone', sa.String(length=48), nullable=True),
    sa.Column('whatsapp', sa.String(length=48), nullable=True),
    sa.Column('address', sa.String(length=320), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_kind_name', 'clients', ['kind', 'display_name'], unique=False)
    op.create_index('ix_client_phone', 'clients', ['phone'], unique=False)
    op.create_index(op.f('ix_clients_created_at'), 'clients', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_display_name'), 'clients', ['display_name'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_kind'), 'clients', ['kind'], unique=False)
    op.create_table('investments',
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('acquisition', 'renovation', 'construction', 'fees', 'marketing', 'other', name='investment_kind'), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('is_recovered', sa.Boolean(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investment_property_date', 'investments', ['property_id', 'spent_on'], unique=False)
    op.create_index(op.f('ix_investments_created_at'), 'investments', ['created_at'], unique=False)
    op.create_index(op.f('ix_investments_kind'), 'investments', ['kind'], unique=False)
    op.create_table('commissions',
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('sale_record_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('basis', sa.Enum('percent', 'fixed', name='commission_basis'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('pending', 'invoiced', 'received', 'written_off', name='commission_status'), nullable=False),
    sa.Column('earned_on', sa.Date(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_record_id'], ['property_sale_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commission_client', 'commissions', ['client_id'], unique=False)
    op.create_index('ix_commission_status_date', 'commissions', ['status', 'earned_on'], unique=False)
    op.create_index(op.f('ix_commissions_created_at'), 'commissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_commissions_earned_on'), 'commissions', ['earned_on'], unique=False)
    op.create_index(op.f('ix_commissions_status'), 'commissions', ['status'], unique=False)
    op.add_column('properties', sa.Column('seller_client_id', sa.UUID(), nullable=True))
    op.add_column('properties', sa.Column('owner_price', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('properties', sa.Column('commission_basis', sa.String(length=16), nullable=True))
    op.add_column('properties', sa.Column('commission_rate', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('properties', sa.Column('commission_amount', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column(
        'properties',
        # server_default is required: the table already holds rows, and a bare
        # NOT NULL add has nothing to put in them.
        sa.Column('commission_in_price', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    op.create_index(op.f('ix_properties_seller_client_id'), 'properties', ['seller_client_id'], unique=False)
    op.create_foreign_key(
        'fk_properties_seller_client', 'properties', 'clients', ['seller_client_id'], ['id'], ondelete='SET NULL',
    )
    op.add_column('property_sale_records', sa.Column('seller_client_id', sa.UUID(), nullable=True))
    op.add_column('property_sale_records', sa.Column('buyer_client_id', sa.UUID(), nullable=True))
    op.add_column(
        'property_sale_records',
        sa.Column('is_historic', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('property_sale_records', sa.Column('recorded_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_property_sale_records_buyer_client_id'), 'property_sale_records', ['buyer_client_id'], unique=False)
    op.create_index(op.f('ix_property_sale_records_seller_client_id'), 'property_sale_records', ['seller_client_id'], unique=False)
    op.create_foreign_key(
        'fk_sale_records_seller_client', 'property_sale_records', 'clients', ['seller_client_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_sale_records_buyer_client', 'property_sale_records', 'clients', ['buyer_client_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_sale_records_recorded_by', 'property_sale_records', 'users', ['recorded_by_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for name in (
        'fk_sale_records_recorded_by',
        'fk_sale_records_buyer_client',
        'fk_sale_records_seller_client',
    ):
        op.drop_constraint(name, 'property_sale_records', type_='foreignkey')
    op.drop_index(op.f('ix_property_sale_records_seller_client_id'), table_name='property_sale_records')
    op.drop_index(op.f('ix_property_sale_records_buyer_client_id'), table_name='property_sale_records')
    op.drop_column('property_sale_records', 'recorded_by_id')
    op.drop_column('property_sale_records', 'is_historic')
    op.drop_column('property_sale_records', 'buyer_client_id')
    op.drop_column('property_sale_records', 'seller_client_id')
    op.drop_constraint('fk_properties_seller_client', 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_seller_client_id'), table_name='properties')
    op.drop_column('properties', 'commission_in_price')
    op.drop_column('properties', 'commission_amount')
    op.drop_column('properties', 'commission_rate')
    op.drop_column('properties', 'commission_basis')
    op.drop_column('properties', 'owner_price')
    op.drop_column('properties', 'seller_client_id')
    op.drop_index(op.f('ix_commissions_status'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_earned_on'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_created_at'), table_name='commissions')
    op.drop_index('ix_commission_status_date', table_name='commissions')
    op.drop_index('ix_commission_client', table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_investments_kind'), table_name='investments')
    op.drop_index(op.f('ix_investments_created_at'), table_name='investments')
    op.drop_index('ix_investment_property_date', table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_clients_kind'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_display_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_created_at'), table_name='clients')
    op.drop_index('ix_client_phone', table_name='clients')
    op.drop_index('ix_client_kind_name', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
    for enum_name in ('client_kind', 'commission_basis', 'commission_status', 'investment_kind'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
