"""property master plan zoning

Revision ID: 4470d47e599d
Revises: 19843612b714
Create Date: 2026-08-24 17:42:29.606536+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4470d47e599d'
down_revision: str | None = '19843612b714'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('master_plan_zone', sa.String(length=160), nullable=True))
    op.add_column('properties', sa.Column('master_plan_note', sa.Text(), nullable=True))
    op.add_column('properties', sa.Column('master_plan_doc_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'master_plan_doc_url')
    op.drop_column('properties', 'master_plan_note')
    op.drop_column('properties', 'master_plan_zone')
    # ### end Alembic commands ###
