"""administrative localities

Revision ID: 4eb0b2daddd9
Revises: fc40902c04da
Create Date: 2026-08-24 21:49:16.435124+00:00
"""
from collections.abc import Sequence

from alembic import op
import geoalchemy2
import sqlalchemy as sa


revision: str = '4eb0b2daddd9'
down_revision: str | None = 'fc40902c04da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localities',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['localities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'name', 'parent_id', name='uq_locality_name')
    )
    op.create_index(op.f('ix_localities_created_at'), 'localities', ['created_at'], unique=False)
    op.create_index(op.f('ix_localities_level'), 'localities', ['level'], unique=False)
    op.create_index(op.f('ix_localities_name'), 'localities', ['name'], unique=False)
    op.create_index(op.f('ix_localities_parent_id'), 'localities', ['parent_id'], unique=False)
    op.create_index(op.f('ix_localities_source_id'), 'localities', ['source_id'], unique=False)
    op.create_index('ix_locality_level_name', 'localities', ['level', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_locality_level_name', table_name='localities')
    op.drop_index(op.f('ix_localities_source_id'), table_name='localities')
    op.drop_index(op.f('ix_localities_parent_id'), table_name='localities')
    op.drop_index(op.f('ix_localities_name'), table_name='localities')
    op.drop_index(op.f('ix_localities_level'), table_name='localities')
    op.drop_index(op.f('ix_localities_created_at'), table_name='localities')
    op.drop_table('localities')
    # ### end Alembic commands ###
