"""buyer property requests and submission owner link

Revision ID: 29bb8246883b
Revises: 96b57dea8ab2
Create Date: 2026-08-04 22:07:14.618522+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '29bb8246883b'
down_revision: str | None = '96b57dea8ab2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_requests',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=240), nullable=True),
    sa.Column('phone', sa.String(length=48), nullable=False),
    sa.Column('intent', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('preferred_areas', sa.String(length=320), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('size_min', sa.Float(), nullable=True),
    sa.Column('bedrooms_min', sa.Integer(), nullable=True),
    sa.Column('timeline', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'matched', 'fulfilled', 'closed', name='property_request_status'), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('matched_property_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['property_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['property_subcategories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_requests_created_at'), 'property_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_property_requests_reference'), 'property_requests', ['reference'], unique=True)
    op.create_index(op.f('ix_property_requests_requested_by_id'), 'property_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_property_requests_status'), 'property_requests', ['status'], unique=False)
    op.create_index('ix_request_district', 'property_requests', ['district'], unique=False)
    op.create_index('ix_request_status_created', 'property_requests', ['status', 'created_at'], unique=False)
    # Autogenerate also proposed dropping the server defaults on
    # `construction_packages.show_price` and `properties.show_on_map`. That is
    # pre-existing drift between the models and the database, not part of this
    # change, and removing those defaults would alter insert behaviour — left
    # alone deliberately.
    op.add_column('seller_submissions', sa.Column('submitted_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_seller_submissions_submitted_by_id'), 'seller_submissions', ['submitted_by_id'], unique=False)
    op.create_foreign_key(
        'fk_seller_submissions_submitted_by_id_users',
        'seller_submissions', 'users', ['submitted_by_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_seller_submissions_submitted_by_id_users', 'seller_submissions', type_='foreignkey'
    )
    op.drop_index(op.f('ix_seller_submissions_submitted_by_id'), table_name='seller_submissions')
    op.drop_column('seller_submissions', 'submitted_by_id')
    op.drop_index('ix_request_status_created', table_name='property_requests')
    op.drop_index('ix_request_district', table_name='property_requests')
    op.drop_index(op.f('ix_property_requests_status'), table_name='property_requests')
    op.drop_index(op.f('ix_property_requests_requested_by_id'), table_name='property_requests')
    op.drop_index(op.f('ix_property_requests_reference'), table_name='property_requests')
    op.drop_index(op.f('ix_property_requests_created_at'), table_name='property_requests')
    op.drop_table('property_requests')
    # `create_table` creates the enum implicitly but `drop_table` does not drop
    # it. Without this, downgrade-then-upgrade fails on "type already exists".
    sa.Enum(name='property_request_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
