"""setting options and select type

Revision ID: 19843612b714
Revises: bde922b7f298
Create Date: 2026-08-24 14:49:21.705229+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '19843612b714'
down_revision: str | None = 'bde922b7f298'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate never notices a new *value* on an existing enum, only new
    # types — so this has to be spelled out or a fresh deploy rejects the
    # dropdown settings the seeder writes.
    op.execute("ALTER TYPE setting_type ADD VALUE IF NOT EXISTS 'select'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'options')
    # ### end Alembic commands ###
