"""seller submissions with owner ids and photos

Revision ID: bdee769e2838
Revises: f0742dcbb484
Create Date: 2026-08-02 19:05:12.997853+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bdee769e2838'
down_revision: str | None = 'f0742dcbb484'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_submissions',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('upi', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=240), nullable=True),
    sa.Column('property_type', sa.String(length=120), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'reviewing', 'accepted', 'rejected', name='seller_submission_status'), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('upload_token', sa.String(length=64), nullable=False),
    sa.Column('upload_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seller_submission_status', 'seller_submissions', ['status', 'created_at'], unique=False)
    op.create_index('ix_seller_submission_upi', 'seller_submissions', ['upi'], unique=False)
    op.create_index(op.f('ix_seller_submissions_created_at'), 'seller_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_seller_submissions_reference'), 'seller_submissions', ['reference'], unique=True)
    op.create_index(op.f('ix_seller_submissions_status'), 'seller_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_seller_submissions_upi'), 'seller_submissions', ['upi'], unique=False)
    op.create_table('seller_submission_owners',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=48), nullable=False),
    sa.Column('email', sa.String(length=240), nullable=True),
    sa.Column('national_id', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['seller_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_submission_owners_created_at'), 'seller_submission_owners', ['created_at'], unique=False)
    op.create_index('ix_submission_owner', 'seller_submission_owners', ['submission_id', 'display_order'], unique=False)
    op.create_table('seller_submission_files',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('id_document', 'property_photo', 'title_deed', 'other', name='submission_file_kind'), nullable=False),
    sa.Column('url', sa.String(length=768), nullable=False),
    sa.Column('original_name', sa.String(length=240), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['seller_submission_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['seller_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_submission_files_created_at'), 'seller_submission_files', ['created_at'], unique=False)
    op.create_index('ix_submission_file', 'seller_submission_files', ['submission_id', 'kind'], unique=False)
    op.alter_column('properties', 'show_on_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('properties', 'show_owner_info',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('properties', 'allow_bidding',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('properties', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('properties', 'allow_bidding',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('properties', 'show_owner_info',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('properties', 'show_on_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index('ix_submission_file', table_name='seller_submission_files')
    op.drop_index(op.f('ix_seller_submission_files_created_at'), table_name='seller_submission_files')
    op.drop_table('seller_submission_files')
    op.drop_index('ix_submission_owner', table_name='seller_submission_owners')
    op.drop_index(op.f('ix_seller_submission_owners_created_at'), table_name='seller_submission_owners')
    op.drop_table('seller_submission_owners')
    op.drop_index(op.f('ix_seller_submissions_upi'), table_name='seller_submissions')
    op.drop_index(op.f('ix_seller_submissions_status'), table_name='seller_submissions')
    op.drop_index(op.f('ix_seller_submissions_reference'), table_name='seller_submissions')
    op.drop_index(op.f('ix_seller_submissions_created_at'), table_name='seller_submissions')
    op.drop_index('ix_seller_submission_upi', table_name='seller_submissions')
    op.drop_index('ix_seller_submission_status', table_name='seller_submissions')
    op.drop_table('seller_submissions')
    # ### end Alembic commands ###
