"""bidding, marketplace visibility and sale history

Revision ID: f0742dcbb484
Revises: 438ca8efca51
Create Date: 2026-08-02 17:35:18.869657+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f0742dcbb484'
down_revision: str | None = '438ca8efca51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_bids',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'withdrawn', 'outbid', name='bid_status'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bid_bidder', 'property_bids', ['bidder_id', 'created_at'], unique=False)
    op.create_index('ix_bid_property_amount', 'property_bids', ['property_id', 'amount'], unique=False)
    op.create_index('ix_bid_property_status', 'property_bids', ['property_id', 'status'], unique=False)
    op.create_index(op.f('ix_property_bids_created_at'), 'property_bids', ['created_at'], unique=False)
    op.create_index(op.f('ix_property_bids_status'), 'property_bids', ['status'], unique=False)
    op.create_table('property_sale_records',
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('reference_number', sa.String(length=40), nullable=False),
    sa.Column('upi', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(length=240), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('sold_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_name', sa.String(length=160), nullable=True),
    sa.Column('owner_contact', sa.String(length=120), nullable=True),
    sa.Column('buyer_name', sa.String(length=160), nullable=True),
    sa.Column('buyer_contact', sa.String(length=120), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('winning_bid_id', sa.UUID(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['property_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['property_subcategories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winning_bid_id'], ['property_bids.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_sale_records_created_at'), 'property_sale_records', ['created_at'], unique=False)
    op.create_index('ix_sale_reference', 'property_sale_records', ['reference_number'], unique=False)
    op.create_index('ix_sale_sold_at', 'property_sale_records', ['sold_at'], unique=False)
    op.create_index('ix_sale_upi', 'property_sale_records', ['upi'], unique=False)
    op.add_column(
        'properties',
        sa.Column('show_on_public', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    op.add_column(
        'properties',
        sa.Column('show_owner_info', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column(
        'properties',
        sa.Column('allow_bidding', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('properties', sa.Column('min_bid', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('properties', sa.Column('bidding_closes_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'properties',
        sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('properties', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_property_reference_number'), 'properties', type_='unique')
    op.drop_constraint(op.f('uq_property_upi'), 'properties', type_='unique')
    op.create_index(op.f('ix_properties_is_archived'), 'properties', ['is_archived'], unique=False)
    op.create_index(op.f('ix_properties_show_on_public'), 'properties', ['show_on_public'], unique=False)
    op.create_index('ix_property_public', 'properties', ['show_on_public', 'is_archived', 'status'], unique=False)
    op.create_index('uq_property_reference_active', 'properties', ['reference_number'], unique=True, postgresql_where=sa.text('is_archived = false'))
    op.create_index('uq_property_upi_active', 'properties', ['upi'], unique=True, postgresql_where=sa.text('is_archived = false AND upi IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_property_upi_active', table_name='properties', postgresql_where=sa.text('is_archived = false AND upi IS NOT NULL'))
    op.drop_index('uq_property_reference_active', table_name='properties', postgresql_where=sa.text('is_archived = false'))
    op.drop_index('ix_property_public', table_name='properties')
    op.drop_index(op.f('ix_properties_show_on_public'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_archived'), table_name='properties')
    op.create_unique_constraint(op.f('uq_property_upi'), 'properties', ['upi'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_property_reference_number'), 'properties', ['reference_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('properties', 'archived_at')
    op.drop_column('properties', 'is_archived')
    op.drop_column('properties', 'bidding_closes_at')
    op.drop_column('properties', 'min_bid')
    op.drop_column('properties', 'allow_bidding')
    op.drop_column('properties', 'show_owner_info')
    op.drop_column('properties', 'show_on_public')
    op.drop_index('ix_sale_upi', table_name='property_sale_records')
    op.drop_index('ix_sale_sold_at', table_name='property_sale_records')
    op.drop_index('ix_sale_reference', table_name='property_sale_records')
    op.drop_index(op.f('ix_property_sale_records_created_at'), table_name='property_sale_records')
    op.drop_table('property_sale_records')
    op.drop_index(op.f('ix_property_bids_status'), table_name='property_bids')
    op.drop_index(op.f('ix_property_bids_created_at'), table_name='property_bids')
    op.drop_index('ix_bid_property_status', table_name='property_bids')
    op.drop_index('ix_bid_property_amount', table_name='property_bids')
    op.drop_index('ix_bid_bidder', table_name='property_bids')
    op.drop_table('property_bids')
    # ### end Alembic commands ###
