"""initial schema

Revision ID: 438ca8efca51
Revises: 
Create Date: 2026-08-02 13:09:27.327471+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '438ca8efca51'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_dates',
    sa.Column('blocked_on', sa.Date(), nullable=False),
    sa.Column('reason_type', sa.String(length=24), nullable=False),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocked_on', 'reason_type', name='uq_blocked_date')
    )
    op.create_index(op.f('ix_blocked_dates_blocked_on'), 'blocked_dates', ['blocked_on'], unique=False)
    op.create_index(op.f('ix_blocked_dates_created_at'), 'blocked_dates', ['created_at'], unique=False)
    op.create_table('captcha_challenges',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('answer_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_captcha_token')
    )
    op.create_index(op.f('ix_captcha_challenges_created_at'), 'captcha_challenges', ['created_at'], unique=False)
    op.create_index(op.f('ix_captcha_challenges_ip_address'), 'captcha_challenges', ['ip_address'], unique=False)
    op.create_index(op.f('ix_captcha_challenges_token'), 'captcha_challenges', ['token'], unique=False)
    op.create_table('construction_packages',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.String(length=40), nullable=False),
    sa.Column('tagline', sa.String(length=240), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_per_sqm', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('duration', sa.String(length=80), nullable=True),
    sa.Column('includes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finishes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_construction_packages_created_at'), 'construction_packages', ['created_at'], unique=False)
    op.create_index(op.f('ix_construction_packages_slug'), 'construction_packages', ['slug'], unique=True)
    op.create_table('consultation_types',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price_label', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('modes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('available_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_types_created_at'), 'consultation_types', ['created_at'], unique=False)
    op.create_index(op.f('ix_consultation_types_slug'), 'consultation_types', ['slug'], unique=True)
    op.create_table('content_blocks',
    sa.Column('page', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('eyebrow', sa.String(length=160), nullable=True),
    sa.Column('title', sa.String(length=320), nullable=True),
    sa.Column('accent', sa.String(length=160), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(length=768), nullable=True),
    sa.Column('cta_label', sa.String(length=120), nullable=True),
    sa.Column('cta_href', sa.String(length=320), nullable=True),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page', 'key', name='uq_block_page_key')
    )
    op.create_index('ix_blocks_page_order', 'content_blocks', ['page', 'display_order'], unique=False)
    op.create_index(op.f('ix_content_blocks_created_at'), 'content_blocks', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_blocks_page'), 'content_blocks', ['page'], unique=False)
    op.create_table('districts',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('province', sa.String(length=80), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_created_at'), 'districts', ['created_at'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=True)
    op.create_index(op.f('ix_districts_province'), 'districts', ['province'], unique=False)
    op.create_table('faqs',
    sa.Column('page', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_faq_page_order', 'faqs', ['page', 'display_order'], unique=False)
    op.create_index(op.f('ix_faqs_created_at'), 'faqs', ['created_at'], unique=False)
    op.create_index(op.f('ix_faqs_page'), 'faqs', ['page'], unique=False)
    op.create_table('job_applications',
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=48), nullable=False),
    sa.Column('role_applied', sa.String(length=64), nullable=False),
    sa.Column('area_covered', sa.String(length=160), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('pitch', sa.Text(), nullable=False),
    sa.Column('portfolio_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_created_at'), 'job_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_applications_email'), 'job_applications', ['email'], unique=False)
    op.create_index(op.f('ix_job_applications_role_applied'), 'job_applications', ['role_applied'], unique=False)
    op.create_index(op.f('ix_job_applications_status'), 'job_applications', ['status'], unique=False)
    op.create_table('market_stats',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('detail', sa.String(length=320), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=320), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_stats_created_at'), 'market_stats', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_stats_key'), 'market_stats', ['key'], unique=True)
    op.create_table('navigation_items',
    sa.Column('menu', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('translation_key', sa.String(length=96), nullable=True),
    sa.Column('href', sa.String(length=320), nullable=False),
    sa.Column('description', sa.String(length=320), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['navigation_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nav_menu_parent_order', 'navigation_items', ['menu', 'parent_id', 'display_order'], unique=False)
    op.create_index(op.f('ix_navigation_items_created_at'), 'navigation_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_navigation_items_menu'), 'navigation_items', ['menu'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_created_at'), 'newsletter_subscribers', ['created_at'], unique=False)
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_table('option_sets',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_sets_created_at'), 'option_sets', ['created_at'], unique=False)
    op.create_index(op.f('ix_option_sets_key'), 'option_sets', ['key'], unique=True)
    op.create_table('property_categories',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('label_rw', sa.String(length=120), nullable=True),
    sa.Column('label_fr', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_active_order', 'property_categories', ['is_active', 'display_order'], unique=False)
    op.create_index(op.f('ix_property_categories_created_at'), 'property_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_property_categories_slug'), 'property_categories', ['slug'], unique=True)
    op.create_table('service_lines',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('tagline', sa.String(length=240), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('division', sa.String(length=40), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('href', sa.String(length=320), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_lines_created_at'), 'service_lines', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_lines_division'), 'service_lines', ['division'], unique=False)
    op.create_index(op.f('ix_service_lines_slug'), 'service_lines', ['slug'], unique=True)
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Enum('string', 'text', 'number', 'boolean', 'json', 'color', 'image', 'url', 'email', name='setting_type'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_settings_group_order', 'site_settings', ['group', 'display_order'], unique=False)
    op.create_index(op.f('ix_site_settings_created_at'), 'site_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_site_settings_group'), 'site_settings', ['group'], unique=False)
    op.create_index(op.f('ix_site_settings_is_public'), 'site_settings', ['is_public'], unique=False)
    op.create_index(op.f('ix_site_settings_key'), 'site_settings', ['key'], unique=True)
    op.create_table('testimonials',
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=160), nullable=False),
    sa.Column('author_role', sa.String(length=160), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('photo_url', sa.String(length=768), nullable=True),
    sa.Column('milestone', sa.String(length=240), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonials_created_at'), 'testimonials', ['created_at'], unique=False)
    op.create_index(op.f('ix_testimonials_is_published'), 'testimonials', ['is_published'], unique=False)
    op.create_table('ui_strings',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('namespace', sa.String(length=32), nullable=False),
    sa.Column('en', sa.Text(), nullable=False),
    sa.Column('rw', sa.Text(), nullable=True),
    sa.Column('fr', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_strings_created_at'), 'ui_strings', ['created_at'], unique=False)
    op.create_index(op.f('ix_ui_strings_key'), 'ui_strings', ['key'], unique=True)
    op.create_index('ix_ui_strings_namespace', 'ui_strings', ['namespace'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'agent', 'admin', 'super_admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'disabled', name='user_status'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('otp_enabled', sa.Boolean(), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('division', sa.String(length=40), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('specialties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('covers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('joined_year', sa.String(length=8), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('deals_closed', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_division'), 'users', ['division'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_full_name_trgm', 'users', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_users_is_public'), 'users', ['is_public'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_table('wealth_cycle_steps',
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wealth_cycle_steps_created_at'), 'wealth_cycle_steps', ['created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=480), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_created', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('contact_messages',
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=48), nullable=True),
    sa.Column('topic', sa.String(length=96), nullable=True),
    sa.Column('budget', sa.String(length=64), nullable=True),
    sa.Column('based_in', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('handled_by_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_index(op.f('ix_contact_messages_status'), 'contact_messages', ['status'], unique=False)
    op.create_index('ix_contact_status_created', 'contact_messages', ['status', 'created_at'], unique=False)
    op.create_table('insights',
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('title', sa.String(length=320), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('cover_url', sa.String(length=768), nullable=True),
    sa.Column('read_time', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=160), nullable=True),
    sa.Column('author_role', sa.String(length=160), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=240), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insight_published_date', 'insights', ['is_published', 'published_at'], unique=False)
    op.create_index('ix_insight_search_trgm', 'insights', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_insights_category'), 'insights', ['category'], unique=False)
    op.create_index(op.f('ix_insights_created_at'), 'insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_insights_is_published'), 'insights', ['is_published'], unique=False)
    op.create_index(op.f('ix_insights_published_at'), 'insights', ['published_at'], unique=False)
    op.create_index(op.f('ix_insights_slug'), 'insights', ['slug'], unique=True)
    op.create_table('otp_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('login', 'email_verify', 'password_reset', name='otp_purpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('challenge', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_challenge'), 'otp_codes', ['challenge'], unique=False)
    op.create_index(op.f('ix_otp_codes_created_at'), 'otp_codes', ['created_at'], unique=False)
    op.create_index('ix_otp_user_purpose_active', 'otp_codes', ['user_id', 'purpose', 'consumed_at'], unique=False)
    op.create_table('property_subcategories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('label_rw', sa.String(length=160), nullable=True),
    sa.Column('label_fr', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('is_land', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['property_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'slug', name='uq_subcategory_slug_per_category')
    )
    op.create_index(op.f('ix_property_subcategories_category_id'), 'property_subcategories', ['category_id'], unique=False)
    op.create_index(op.f('ix_property_subcategories_created_at'), 'property_subcategories', ['created_at'], unique=False)
    op.create_index(op.f('ix_property_subcategories_slug'), 'property_subcategories', ['slug'], unique=False)
    op.create_index('ix_subcategories_active_order', 'property_subcategories', ['is_active', 'display_order'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=320), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_user_revoked', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_table('properties',
    sa.Column('reference_number', sa.String(length=40), nullable=False),
    sa.Column('upi', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('title_rw', sa.String(length=240), nullable=True),
    sa.Column('title_fr', sa.String(length=240), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_rw', sa.Text(), nullable=True),
    sa.Column('summary_fr', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=240), nullable=True),
    sa.Column('province', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('cell', sa.String(length=80), nullable=True),
    sa.Column('village', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('gis_coordinates', sa.String(length=120), nullable=True),
    sa.Column('boundary_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('boundary_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('boundary_area_sqm', sa.Float(), nullable=True),
    sa.Column('parcel_id', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('built_area', sa.Float(), nullable=True),
    sa.Column('land_use', sa.String(length=120), nullable=True),
    sa.Column('right_type', sa.String(length=120), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'available', 'reserved', 'under_offer', 'sold', 'rented', 'withdrawn', 'rejected', name='property_status'), nullable=False),
    sa.Column('intent', sa.Enum('sale', 'rent', 'both', name='listing_intent'), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('is_negotiable', sa.Boolean(), nullable=False),
    sa.Column('projected_yield', sa.Float(), nullable=True),
    sa.Column('appreciation', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parcel_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video_link', sa.String(length=512), nullable=True),
    sa.Column('video_360_url', sa.String(length=512), nullable=True),
    sa.Column('vr_tour_url', sa.String(length=512), nullable=True),
    sa.Column('vr_tour_provider', sa.String(length=40), nullable=True),
    sa.Column('panorama_scenes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('drone_footage_url', sa.String(length=512), nullable=True),
    sa.Column('owner_name', sa.String(length=160), nullable=True),
    sa.Column('owner_contact', sa.String(length=120), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('uploader_type', sa.Enum('agency', 'broker', 'seller', name='uploader_type'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=240), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['property_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['property_subcategories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number', name='uq_property_reference_number'),
    sa.UniqueConstraint('upi', name='uq_property_upi')
    )
    op.create_index(op.f('ix_properties_agent_id'), 'properties', ['agent_id'], unique=False)
    op.create_index(op.f('ix_properties_bedrooms'), 'properties', ['bedrooms'], unique=False)
    op.create_index(op.f('ix_properties_category_id'), 'properties', ['category_id'], unique=False)
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    op.create_index(op.f('ix_properties_district'), 'properties', ['district'], unique=False)
    op.create_index(op.f('ix_properties_intent'), 'properties', ['intent'], unique=False)
    op.create_index(op.f('ix_properties_is_verified'), 'properties', ['is_verified'], unique=False)
    op.create_index(op.f('ix_properties_province'), 'properties', ['province'], unique=False)
    op.create_index(op.f('ix_properties_published_at'), 'properties', ['published_at'], unique=False)
    op.create_index(op.f('ix_properties_reference_number'), 'properties', ['reference_number'], unique=False)
    op.create_index(op.f('ix_properties_sector'), 'properties', ['sector'], unique=False)
    op.create_index(op.f('ix_properties_size'), 'properties', ['size'], unique=False)
    op.create_index(op.f('ix_properties_slug'), 'properties', ['slug'], unique=True)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index(op.f('ix_properties_subcategory_id'), 'properties', ['subcategory_id'], unique=False)
    op.create_index(op.f('ix_properties_upi'), 'properties', ['upi'], unique=False)
    op.create_index(op.f('ix_properties_uploaded_by_id'), 'properties', ['uploaded_by_id'], unique=False)
    op.create_index('ix_property_category_status', 'properties', ['category_id', 'status'], unique=False)
    op.create_index('ix_property_details_gin', 'properties', ['details'], unique=False, postgresql_using='gin')
    op.create_index('ix_property_district_status', 'properties', ['district', 'status'], unique=False)
    op.create_index('ix_property_featured', 'properties', ['is_featured', 'status'], unique=False)
    op.create_index('ix_property_price', 'properties', ['price'], unique=False)
    op.create_index('ix_property_search_trgm', 'properties', ['search_text'], unique=False, postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.create_index('ix_property_status_intent_created', 'properties', ['status', 'intent', 'created_at'], unique=False)
    op.create_table('property_form_fields',
    sa.Column('subcategory_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('label_rw', sa.String(length=240), nullable=True),
    sa.Column('label_fr', sa.String(length=240), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=240), nullable=True),
    sa.Column('type', sa.Enum('text', 'number', 'select', 'radio', 'checkbox', 'multiselect', 'section_header', 'date', 'textarea', name='form_field_type'), nullable=False),
    sa.Column('width', sa.Enum('full', 'half', 'third', name='form_field_width'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('conditional', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['property_subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcategory_id', 'name', name='uq_field_name_per_subcategory')
    )
    op.create_index('ix_fields_subcat_order', 'property_form_fields', ['subcategory_id', 'display_order'], unique=False)
    op.create_index(op.f('ix_property_form_fields_created_at'), 'property_form_fields', ['created_at'], unique=False)
    op.create_table('bookings',
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('consultation_type_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=48), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=64), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled', 'no_show', name='booking_status'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consultation_type_id'], ['consultation_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consultation_type_id', 'scheduled_date', 'scheduled_time', 'agent_id', name='uq_booking_slot')
    )
    op.create_index('ix_booking_date_status', 'bookings', ['scheduled_date', 'status'], unique=False)
    op.create_index(op.f('ix_bookings_agent_id'), 'bookings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_email'), 'bookings', ['email'], unique=False)
    op.create_index(op.f('ix_bookings_property_id'), 'bookings', ['property_id'], unique=False)
    op.create_index(op.f('ix_bookings_reference'), 'bookings', ['reference'], unique=True)
    op.create_index(op.f('ix_bookings_scheduled_date'), 'bookings', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('property_enquiries',
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=48), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enquiry_property_status', 'property_enquiries', ['property_id', 'status'], unique=False)
    op.create_index(op.f('ix_property_enquiries_assigned_to_id'), 'property_enquiries', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_property_enquiries_created_at'), 'property_enquiries', ['created_at'], unique=False)
    op.create_index(op.f('ix_property_enquiries_email'), 'property_enquiries', ['email'], unique=False)
    op.create_index(op.f('ix_property_enquiries_property_id'), 'property_enquiries', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_enquiries_status'), 'property_enquiries', ['status'], unique=False)
    op.create_table('property_media',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('image', 'floorplan', 'document', 'video', 'video_360', 'panorama', 'vr_tour', 'drone', name='media_kind'), nullable=False),
    sa.Column('url', sa.String(length=768), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=768), nullable=True),
    sa.Column('caption', sa.String(length=240), nullable=True),
    sa.Column('alt_text', sa.String(length=240), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_property_kind_order', 'property_media', ['property_id', 'kind', 'display_order'], unique=False)
    op.create_index(op.f('ix_property_media_created_at'), 'property_media', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_media_created_at'), table_name='property_media')
    op.drop_index('ix_media_property_kind_order', table_name='property_media')
    op.drop_table('property_media')
    op.drop_index(op.f('ix_property_enquiries_status'), table_name='property_enquiries')
    op.drop_index(op.f('ix_property_enquiries_property_id'), table_name='property_enquiries')
    op.drop_index(op.f('ix_property_enquiries_email'), table_name='property_enquiries')
    op.drop_index(op.f('ix_property_enquiries_created_at'), table_name='property_enquiries')
    op.drop_index(op.f('ix_property_enquiries_assigned_to_id'), table_name='property_enquiries')
    op.drop_index('ix_enquiry_property_status', table_name='property_enquiries')
    op.drop_table('property_enquiries')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_scheduled_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_reference'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_property_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_email'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_agent_id'), table_name='bookings')
    op.drop_index('ix_booking_date_status', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_property_form_fields_created_at'), table_name='property_form_fields')
    op.drop_index('ix_fields_subcat_order', table_name='property_form_fields')
    op.drop_table('property_form_fields')
    op.drop_index('ix_property_status_intent_created', table_name='properties')
    op.drop_index('ix_property_search_trgm', table_name='properties', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.drop_index('ix_property_price', table_name='properties')
    op.drop_index('ix_property_featured', table_name='properties')
    op.drop_index('ix_property_district_status', table_name='properties')
    op.drop_index('ix_property_details_gin', table_name='properties', postgresql_using='gin')
    op.drop_index('ix_property_category_status', table_name='properties')
    op.drop_index(op.f('ix_properties_uploaded_by_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_upi'), table_name='properties')
    op.drop_index(op.f('ix_properties_subcategory_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_slug'), table_name='properties')
    op.drop_index(op.f('ix_properties_size'), table_name='properties')
    op.drop_index(op.f('ix_properties_sector'), table_name='properties')
    op.drop_index(op.f('ix_properties_reference_number'), table_name='properties')
    op.drop_index(op.f('ix_properties_published_at'), table_name='properties')
    op.drop_index(op.f('ix_properties_province'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_verified'), table_name='properties')
    op.drop_index(op.f('ix_properties_intent'), table_name='properties')
    op.drop_index(op.f('ix_properties_district'), table_name='properties')
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    op.drop_index(op.f('ix_properties_category_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_bedrooms'), table_name='properties')
    op.drop_index(op.f('ix_properties_agent_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index('ix_refresh_user_revoked', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_subcategories_active_order', table_name='property_subcategories')
    op.drop_index(op.f('ix_property_subcategories_slug'), table_name='property_subcategories')
    op.drop_index(op.f('ix_property_subcategories_created_at'), table_name='property_subcategories')
    op.drop_index(op.f('ix_property_subcategories_category_id'), table_name='property_subcategories')
    op.drop_table('property_subcategories')
    op.drop_index('ix_otp_user_purpose_active', table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_created_at'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_challenge'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_insights_slug'), table_name='insights')
    op.drop_index(op.f('ix_insights_published_at'), table_name='insights')
    op.drop_index(op.f('ix_insights_is_published'), table_name='insights')
    op.drop_index(op.f('ix_insights_created_at'), table_name='insights')
    op.drop_index(op.f('ix_insights_category'), table_name='insights')
    op.drop_index('ix_insight_search_trgm', table_name='insights', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_insight_published_date', table_name='insights')
    op.drop_table('insights')
    op.drop_index('ix_contact_status_created', table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_status'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_wealth_cycle_steps_created_at'), table_name='wealth_cycle_steps')
    op.drop_table('wealth_cycle_steps')
    op.drop_index('ix_users_role_status', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_is_public'), table_name='users')
    op.drop_index('ix_users_full_name_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_division'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_ui_strings_namespace', table_name='ui_strings')
    op.drop_index(op.f('ix_ui_strings_key'), table_name='ui_strings')
    op.drop_index(op.f('ix_ui_strings_created_at'), table_name='ui_strings')
    op.drop_table('ui_strings')
    op.drop_index(op.f('ix_testimonials_is_published'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_created_at'), table_name='testimonials')
    op.drop_table('testimonials')
    op.drop_index(op.f('ix_site_settings_key'), table_name='site_settings')
    op.drop_index(op.f('ix_site_settings_is_public'), table_name='site_settings')
    op.drop_index(op.f('ix_site_settings_group'), table_name='site_settings')
    op.drop_index(op.f('ix_site_settings_created_at'), table_name='site_settings')
    op.drop_index('ix_settings_group_order', table_name='site_settings')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_service_lines_slug'), table_name='service_lines')
    op.drop_index(op.f('ix_service_lines_division'), table_name='service_lines')
    op.drop_index(op.f('ix_service_lines_created_at'), table_name='service_lines')
    op.drop_table('service_lines')
    op.drop_index(op.f('ix_property_categories_slug'), table_name='property_categories')
    op.drop_index(op.f('ix_property_categories_created_at'), table_name='property_categories')
    op.drop_index('ix_categories_active_order', table_name='property_categories')
    op.drop_table('property_categories')
    op.drop_index(op.f('ix_option_sets_key'), table_name='option_sets')
    op.drop_index(op.f('ix_option_sets_created_at'), table_name='option_sets')
    op.drop_table('option_sets')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_created_at'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_navigation_items_menu'), table_name='navigation_items')
    op.drop_index(op.f('ix_navigation_items_created_at'), table_name='navigation_items')
    op.drop_index('ix_nav_menu_parent_order', table_name='navigation_items')
    op.drop_table('navigation_items')
    op.drop_index(op.f('ix_market_stats_key'), table_name='market_stats')
    op.drop_index(op.f('ix_market_stats_created_at'), table_name='market_stats')
    op.drop_table('market_stats')
    op.drop_index(op.f('ix_job_applications_status'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_role_applied'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_email'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_created_at'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_faqs_page'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_created_at'), table_name='faqs')
    op.drop_index('ix_faq_page_order', table_name='faqs')
    op.drop_table('faqs')
    op.drop_index(op.f('ix_districts_province'), table_name='districts')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_created_at'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_content_blocks_page'), table_name='content_blocks')
    op.drop_index(op.f('ix_content_blocks_created_at'), table_name='content_blocks')
    op.drop_index('ix_blocks_page_order', table_name='content_blocks')
    op.drop_table('content_blocks')
    op.drop_index(op.f('ix_consultation_types_slug'), table_name='consultation_types')
    op.drop_index(op.f('ix_consultation_types_created_at'), table_name='consultation_types')
    op.drop_table('consultation_types')
    op.drop_index(op.f('ix_construction_packages_slug'), table_name='construction_packages')
    op.drop_index(op.f('ix_construction_packages_created_at'), table_name='construction_packages')
    op.drop_table('construction_packages')
    op.drop_index(op.f('ix_captcha_challenges_token'), table_name='captcha_challenges')
    op.drop_index(op.f('ix_captcha_challenges_ip_address'), table_name='captcha_challenges')
    op.drop_index(op.f('ix_captcha_challenges_created_at'), table_name='captcha_challenges')
    op.drop_table('captcha_challenges')
    op.drop_index(op.f('ix_blocked_dates_created_at'), table_name='blocked_dates')
    op.drop_index(op.f('ix_blocked_dates_blocked_on'), table_name='blocked_dates')
    op.drop_table('blocked_dates')
    # ### end Alembic commands ###
