"""package price visibility and map publishing

Revision ID: 96b57dea8ab2
Revises: bdee769e2838
Create Date: 2026-08-02 20:03:21.948093+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '96b57dea8ab2'
down_revision: str | None = 'bdee769e2838'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction_packages', sa.Column('show_price', sa.Boolean(), nullable=False))
    op.add_column('construction_packages', sa.Column('price_note', sa.String(length=240), nullable=True))
    op.add_column('construction_packages', sa.Column('suited_to', sa.String(length=240), nullable=True))
    op.add_column('properties', sa.Column('show_on_map', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'show_on_map')
    op.drop_column('construction_packages', 'suited_to')
    op.drop_column('construction_packages', 'price_note')
    op.drop_column('construction_packages', 'show_price')
    # ### end Alembic commands ###
