"""seller submission cell and village

Revision ID: 62ba32190706
Revises: fc986503bb00
Create Date: 2026-08-24 22:18:14.442300+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '62ba32190706'
down_revision: str | None = 'fc986503bb00'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_submissions', sa.Column('cell', sa.String(length=80), nullable=True))
    op.add_column('seller_submissions', sa.Column('village', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_submissions', 'village')
    op.drop_column('seller_submissions', 'cell')
    # ### end Alembic commands ###
