"""
The listing forms, seeded into the database.

Extends the original twenty with a much deeper agricultural section — the brief
asked us to cover "everything that might be on agricultural land use", so that
category now models soil, water rights, irrigation, storage, livestock,
processing, certification and access, not just crops.
"""

YES_NO = ["Yes", "No"]
CROP_SIZES = ["Young", "Medium", "Mature"]
COVERAGE_RATIO = [
    "Less than 25%", "Between 25% – 50%", "Between 50% – 75%", "Above 75%",
]
FENCE_MATERIALS = [
    "No Information", "Concrete/Cement", "Wired", "Wood/Grass", "Brick/Block",
    "Steel", "Natural Stone", "Live hedge",
]
BUILDING_CONDITIONS = ["Poor", "Fair", "Good", "Excellent"]
ROOF_TYPES = ["Double-Pitch", "Mono-Pitch", "Versatile", "Flat roof"]
WALL_MATERIALS = [
    "Clay burnt Bricks", "Adobe blocks", "Cement blocks", "Reinforced concrete",
    "Non-reinforced concrete", "Wood and mud",
]
ROOF_COVERING = [
    "Corrugated Iron Sheets", "Versatile Sheets", "Tile", "Traditional tiles",
    "Reinforced Concrete", "Grass",
]
FLOOR_MATERIALS = ["Mud floor", "Sand Cement creed", "Floor tiles", "Wood", "Texture"]
PRODUCT_TYPES = [
    "Potatoes/Cassava", "Vegetables", "Maize/Sorghum/Wheat/Corn", "Rice", "Banana",
    "Coffee", "Tea", "Fruits", "Other",
]
PARKING_MATERIALS = [
    "Cabro Blocks", "Concrete Pavement", "Clay Bricks/Blocks", "Natural Stone",
    "Gravel", "Missing",
]
SEWAGE_TYPES = ["Central Sewage System", "Septic Tank", "Pit latrines", "Missing"]
AMENITIES = [
    "Swimming pool", "Gym & fitness", "Car parking", "Garden",
    "Sports pitch (basketball, football, Tennis, any others)",
    "Kids outdoor play equipment", "Laundry services", "EV Charging Stations",
    "Any other, Please specify",
]
INDUSTRIAL_INFRA = [
    "Loading Docks & Ramps", "Internal Road Networks Murram",
    "Internal Road Networks Tarmac", "Backup Generators", "Water Treatment Plant",
    "Gas & Fuel Storage", "Conveyor & Material handling System", "Weighbridge",
]

# ---- agricultural vocabulary -------------------------------------------------
SOIL_TYPES = [
    "Clay", "Loam", "Sandy loam", "Sandy", "Silt", "Volcanic (Andosol)",
    "Lateritic", "Peat / Marshland", "Rocky",
]
SOIL_FERTILITY = ["Low", "Moderate", "Good", "Very good"]
SOIL_PH = ["Strongly acidic (<5.5)", "Acidic (5.5–6.5)", "Neutral (6.5–7.5)", "Alkaline (>7.5)", "Not tested"]
TOPOGRAPHY = ["Flat (0–5%)", "Gentle slope (5–15%)", "Moderate slope (15–30%)", "Steep (>30%)", "Terraced"]
EROSION_CONTROL = [
    "Progressive terraces", "Radical terraces", "Contour bunds", "Grass strips",
    "Agroforestry trees", "Check dams", "None",
]
WATER_SOURCES = [
    "River / stream", "Lake", "Borehole", "Shallow well", "Rainwater harvesting",
    "Public water network", "Irrigation scheme", "None",
]
IRRIGATION_TYPES = [
    "Gravity / furrow", "Drip", "Sprinkler", "Centre pivot", "Manual (watering can)",
    "Pump-fed hose", "None",
]
WATER_RELIABILITY = ["Year-round", "Seasonal (rainy season only)", "Intermittent", "Unreliable"]
FARMING_SYSTEM = [
    "Subsistence", "Semi-commercial", "Commercial", "Cooperative-managed",
    "Contract farming", "Agroforestry", "Organic",
]
LIVESTOCK_TYPES = [
    "Dairy cattle", "Beef cattle", "Goats", "Sheep", "Pigs", "Poultry (layers)",
    "Poultry (broilers)", "Rabbits", "Bees / apiary", "Fish ponds", "None",
]
FARM_STRUCTURES = [
    "Cattle shed / kraal", "Poultry house", "Piggery", "Milking parlour",
    "Grain store", "Cold store", "Drying yard / shed", "Greenhouse / tunnel",
    "Nursery / seedbed", "Water reservoir / tank", "Silage pit",
    "Machinery shed", "Farm office", "Worker housing",
]
FARM_EQUIPMENT = [
    "Tractor", "Power tiller", "Plough / harrow", "Planter", "Sprayer",
    "Irrigation pump", "Milking machine", "Feed mixer", "Solar dryer",
    "Generator", "None",
]
CERTIFICATIONS = [
    "Organic certified", "Rainforest Alliance", "Fairtrade", "GlobalG.A.P.",
    "UTZ / RA coffee", "NAEB registered", "None",
]
ROAD_ACCESS = ["Tarmac road", "All-weather murram", "Dry-season track", "Footpath only"]
MARKET_DISTANCE = ["Under 5 km", "5–15 km", "15–30 km", "Over 30 km"]
LAND_TENURE = ["Freehold", "Leasehold", "Customary", "Cooperative share", "Under dispute"]


def building_base() -> list[dict]:
    return [
        {"name": "condition", "label": "Building Condition", "type": "select",
         "options": BUILDING_CONDITIONS, "width": "half"},
        {"name": "built_area", "label": "Built-up Area (sqm)", "type": "number",
         "width": "half", "unit": "sqm"},
        {"name": "building_type", "label": "Building Type", "type": "select",
         "options": ["Detached building", "Semi-Detached building", "Terrace/Row House"],
         "width": "half"},
        {"name": "floors", "label": "Number of Floors", "type": "number", "width": "half"},
        {"name": "roof_type", "label": "Roof Type", "type": "select",
         "options": ROOF_TYPES, "width": "half"},
        {"name": "roof_material", "label": "Roof Covering Material", "type": "select",
         "options": ROOF_COVERING, "width": "half"},
        {"name": "wall_material", "label": "Wall Material", "type": "select",
         "options": WALL_MATERIALS, "width": "half"},
        {"name": "floor_material", "label": "Floor Material", "type": "select",
         "options": FLOOR_MATERIALS, "width": "half"},
        {"name": "under_construction", "label": "Is this building under construction?",
         "type": "radio", "options": YES_NO, "width": "full"},
        {"name": "construction_year", "label": "Year of Construction", "type": "number",
         "width": "full", "conditional": {"field": "under_construction", "value": "No"}},
    ]


def land_infra() -> list[dict]:
    return [
        {"name": "has_electricity", "label": "Electricity", "type": "radio",
         "options": YES_NO, "width": "half"},
        {"name": "has_water", "label": "Water", "type": "radio",
         "options": YES_NO, "width": "half"},
        {"name": "has_parking", "label": "Is there any car parking?", "type": "radio",
         "options": YES_NO, "width": "full"},
        {"name": "parking_material", "label": "Parking Space Material", "type": "select",
         "options": PARKING_MATERIALS, "width": "half",
         "conditional": {"field": "has_parking", "value": "Yes"}},
        {"name": "parking_capacity", "label": "No. of Cars on Parking", "type": "number",
         "width": "half", "conditional": {"field": "has_parking", "value": "Yes"}},
        {"name": "sewage_type", "label": "Sewage", "type": "select",
         "options": SEWAGE_TYPES, "width": "full"},
        {"name": "has_fence", "label": "Is there any fence?", "type": "radio",
         "options": YES_NO, "width": "full"},
        {"name": "fence_material", "label": "Fence Material", "type": "select",
         "options": FENCE_MATERIALS, "width": "full",
         "conditional": {"field": "has_fence", "value": "Yes"}},
    ]


def agri_land_base() -> list[dict]:
    """Soil, terrain, water and access — common to every agricultural form."""
    return [
        {"name": "hdr_soil", "label": "Soil & terrain", "type": "section_header", "width": "full"},
        {"name": "soil_type", "label": "Dominant Soil Type", "type": "select",
         "options": SOIL_TYPES, "width": "half"},
        {"name": "soil_fertility", "label": "Soil Fertility", "type": "select",
         "options": SOIL_FERTILITY, "width": "half"},
        {"name": "soil_ph", "label": "Soil pH", "type": "select", "options": SOIL_PH,
         "width": "half"},
        {"name": "soil_depth", "label": "Topsoil Depth (cm)", "type": "number",
         "width": "half", "unit": "cm"},
        {"name": "topography", "label": "Topography", "type": "select",
         "options": TOPOGRAPHY, "width": "half"},
        {"name": "altitude", "label": "Altitude (m above sea level)", "type": "number",
         "width": "half", "unit": "m"},
        {"name": "erosion_control", "label": "Erosion Control in Place", "type": "multiselect",
         "options": EROSION_CONTROL, "width": "full"},
        {"name": "is_marshland", "label": "Is any part marshland?", "type": "radio",
         "options": YES_NO, "width": "half"},
        {"name": "flood_risk", "label": "Known flood risk?", "type": "radio",
         "options": YES_NO, "width": "half"},

        {"name": "hdr_water", "label": "Water & irrigation", "type": "section_header",
         "width": "full"},
        {"name": "water_sources", "label": "Water Sources on or near the Parcel",
         "type": "multiselect", "options": WATER_SOURCES, "width": "full"},
        {"name": "water_reliability", "label": "Water Availability", "type": "select",
         "options": WATER_RELIABILITY, "width": "half"},
        {"name": "distance_to_water", "label": "Distance to Nearest Water Source (m)",
         "type": "number", "width": "half", "unit": "m"},
        {"name": "irrigation", "label": "Is the land irrigated?", "type": "radio",
         "options": YES_NO, "width": "full"},
        {"name": "irrigation_type", "label": "Irrigation Method", "type": "select",
         "options": IRRIGATION_TYPES, "width": "half",
         "conditional": {"field": "irrigation", "value": "Yes"}},
        {"name": "irrigated_area", "label": "Irrigated Area (ha)", "type": "number",
         "width": "half", "unit": "ha",
         "conditional": {"field": "irrigation", "value": "Yes"}},
        {"name": "has_water_permit", "label": "Water abstraction permit held?",
         "type": "radio", "options": YES_NO, "width": "full",
         "conditional": {"field": "irrigation", "value": "Yes"}},

        {"name": "hdr_access", "label": "Access & market", "type": "section_header",
         "width": "full"},
        {"name": "road_access", "label": "Road Access", "type": "select",
         "options": ROAD_ACCESS, "width": "half"},
        {"name": "market_distance", "label": "Distance to Nearest Market", "type": "select",
         "options": MARKET_DISTANCE, "width": "half"},
        {"name": "has_electricity", "label": "Electricity on the parcel", "type": "radio",
         "options": YES_NO, "width": "half"},
        {"name": "land_tenure", "label": "Tenure", "type": "select",
         "options": LAND_TENURE, "width": "half"},
        {"name": "has_fence", "label": "Is there any fence?", "type": "radio",
         "options": YES_NO, "width": "full"},
        {"name": "fence_material", "label": "Fence Material", "type": "select",
         "options": FENCE_MATERIALS, "width": "full",
         "conditional": {"field": "has_fence", "value": "Yes"}},
    ]


FORM_CONFIG: list[dict] = [
    # ============================================================ 1. FOREST
    {
        "slug": "forest", "label": "Forest", "icon": "TreePine", "display_order": 1,
        "description": "Woodlots, plantations and natural forest parcels.",
        "subcategories": [
            {
                "slug": "forest_plot", "label": "Forest Plot", "is_land": True,
                "fields": [
                    {"name": "products", "label": "Product Type (Choose main three)",
                     "type": "multiselect", "options": PRODUCT_TYPES, "width": "full"},
                    {"name": "species", "label": "Dominant Species", "type": "text",
                     "width": "half", "placeholder": "Eucalyptus, Pine, Grevillea…"},
                    {"name": "crop_size", "label": "Crop Size", "type": "select",
                     "options": CROP_SIZES, "width": "half"},
                    {"name": "coverage", "label": "Crop Coverage Ratio", "type": "select",
                     "options": COVERAGE_RATIO, "width": "half"},
                    {"name": "stand_age", "label": "Stand Age (years)", "type": "number",
                     "width": "half", "unit": "years"},
                    {"name": "topography", "label": "Topography", "type": "select",
                     "options": TOPOGRAPHY, "width": "half"},
                    {"name": "road_access", "label": "Road Access", "type": "select",
                     "options": ROAD_ACCESS, "width": "half"},
                    {"name": "harvest_permit", "label": "Harvesting permit in place?",
                     "type": "radio", "options": YES_NO, "width": "full"},
                    {"name": "has_fence", "label": "Is there any fence?", "type": "radio",
                     "options": YES_NO, "width": "full"},
                    {"name": "fence_material", "label": "Fence Material", "type": "select",
                     "options": FENCE_MATERIALS, "width": "full",
                     "conditional": {"field": "has_fence", "value": "Yes"}},
                ],
            }
        ],
    },
    # ============================================================ 2. AGRICULTURAL
    {
        "slug": "agricultural", "label": "Agricultural", "icon": "Tractor", "display_order": 2,
        "description": "Cropland, livestock holdings, plantations and agri-infrastructure.",
        "subcategories": [
            {
                "slug": "seasonal_crops", "label": "Farmland for seasonal crops", "is_land": True,
                "fields": [
                    {"name": "hdr_crops", "label": "Cropping", "type": "section_header",
                     "width": "full"},
                    {"name": "seasonal", "label": "Seasonal Crops", "type": "radio",
                     "options": YES_NO, "width": "half"},
                    {"name": "perennial", "label": "Perennial Crops", "type": "radio",
                     "options": YES_NO, "width": "half"},
                    {"name": "products", "label": "Product Type (Choose main three)",
                     "type": "multiselect", "options": PRODUCT_TYPES, "width": "full"},
                    {"name": "farming_system", "label": "Farming System", "type": "select",
                     "options": FARMING_SYSTEM, "width": "half"},
                    {"name": "crop_size", "label": "Crop Size", "type": "select",
                     "options": CROP_SIZES, "width": "half"},
                    {"name": "coverage", "label": "Crop Coverage Ratio", "type": "select",
                     "options": COVERAGE_RATIO, "width": "half"},
                    {"name": "cropping_seasons", "label": "Cropping Seasons per Year",
                     "type": "number", "width": "half"},
                    {"name": "yield_per_ha", "label": "Average Yield (tonnes/ha)",
                     "type": "number", "width": "half", "unit": "t/ha"},
                    {"name": "certifications", "label": "Certifications Held",
                     "type": "multiselect", "options": CERTIFICATIONS, "width": "full"},
                    *agri_land_base(),
                    {"name": "hdr_infra", "label": "On-farm infrastructure",
                     "type": "section_header", "width": "full"},
                    {"name": "farm_structures", "label": "Structures on the Parcel",
                     "type": "multiselect", "options": FARM_STRUCTURES, "width": "full"},
                    {"name": "farm_equipment", "label": "Equipment Included in Sale",
                     "type": "multiselect", "options": FARM_EQUIPMENT, "width": "full"},
                    {"name": "storage_capacity", "label": "Storage Capacity (tonnes)",
                     "type": "number", "width": "half", "unit": "t"},
                    {"name": "labour_available", "label": "Local Labour Readily Available?",
                     "type": "radio", "options": YES_NO, "width": "half"},
                ],
            },
            {
                "slug": "plantation", "label": "Plantation (coffee, tea, fruit)", "is_land": True,
                "fields": [
                    {"name": "hdr_plantation", "label": "Plantation", "type": "section_header",
                     "width": "full"},
                    {"name": "crop", "label": "Main Crop", "type": "select",
                     "options": ["Coffee", "Tea", "Banana", "Avocado", "Macadamia",
                                 "Mango", "Passion fruit", "Pineapple", "Other"],
                     "width": "half"},
                    {"name": "variety", "label": "Variety / Cultivar", "type": "text",
                     "width": "half"},
                    {"name": "tree_count", "label": "Number of Trees / Stools",
                     "type": "number", "width": "half"},
                    {"name": "planting_year", "label": "Year Planted", "type": "number",
                     "width": "half"},
                    {"name": "crop_size", "label": "Crop Maturity", "type": "select",
                     "options": CROP_SIZES, "width": "half"},
                    {"name": "annual_output", "label": "Annual Output (kg)", "type": "number",
                     "width": "half", "unit": "kg"},
                    {"name": "buyer_contract", "label": "Existing off-take contract?",
                     "type": "radio", "options": YES_NO, "width": "half"},
                    {"name": "certifications", "label": "Certifications Held",
                     "type": "multiselect", "options": CERTIFICATIONS, "width": "full"},
                    *agri_land_base(),
                    {"name": "hdr_processing", "label": "Processing", "type": "section_header",
                     "width": "full"},
                    {"name": "has_processing", "label": "On-site processing facility?",
                     "type": "radio", "options": YES_NO, "width": "half"},
                    {"name": "processing_type", "label": "Processing Type", "type": "text",
                     "width": "half",
                     "conditional": {"field": "has_processing", "value": "Yes"}},
                    {"name": "farm_structures", "label": "Structures on the Parcel",
                     "type": "multiselect", "options": FARM_STRUCTURES, "width": "full"},
                ],
            },
            {
                "slug": "livestock_farm", "label": "Livestock Farm", "is_land": True,
                "fields": [
                    {"name": "hdr_livestock", "label": "Livestock", "type": "section_header",
                     "width": "full"},
                    {"name": "livestock_types", "label": "Livestock Kept", "type": "multiselect",
                     "options": LIVESTOCK_TYPES, "width": "full"},
                    {"name": "herd_size", "label": "Total Head Count", "type": "number",
                     "width": "half"},
                    {"name": "daily_output", "label": "Daily Output (litres / eggs / kg)",
                     "type": "number", "width": "half"},
                    {"name": "grazing_area", "label": "Grazing Area (ha)", "type": "number",
                     "width": "half", "unit": "ha"},
                    {"name": "fodder_grown", "label": "Fodder grown on site?", "type": "radio",
                     "options": YES_NO, "width": "half"},
                    {"name": "vet_access", "label": "Veterinary Services Nearby?",
                     "type": "radio", "options": YES_NO, "width": "half"},
                    {"name": "livestock_included", "label": "Are the animals included in the price?",
                     "type": "radio", "options": YES_NO, "width": "half"},
                    *agri_land_base(),
                    {"name": "hdr_structures", "label": "Housing & handling",
                     "type": "section_header", "width": "full"},
                    {"name": "farm_structures", "label": "Structures on the Parcel",
                     "type": "multiselect", "options": FARM_STRUCTURES, "width": "full"},
                    {"name": "farm_equipment", "label": "Equipment Included",
                     "type": "multiselect", "options": FARM_EQUIPMENT, "width": "full"},
                    {"name": "waste_management", "label": "Manure / Waste Management",
                     "type": "select",
                     "options": ["Biogas digester", "Compost pit", "Slurry tank",
                                 "Spread on fields", "None"],
                     "width": "full"},
                ],
            },
            {
                "slug": "family_house", "label": "Farmers Family House",
                "fields": [
                    *building_base(),
                    {"name": "hdr_accom", "label": "Accommodation Details",
                     "type": "section_header", "width": "full"},
                    {"name": "units", "label": "Number of Units that can accommodate one family",
                     "type": "number", "width": "full"},
                    {"name": "bedrooms", "label": "Bedrooms", "type": "number", "width": "half"},
                    {"name": "sitting_rooms", "label": "Sitting rooms", "type": "number",
                     "width": "half"},
                    {"name": "bathrooms", "label": "Bathrooms", "type": "number", "width": "half"},
                    {"name": "store_rooms", "label": "Store rooms", "type": "number",
                     "width": "half"},
                    {"name": "kitchen", "label": "Kitchen", "type": "number", "width": "half"},
                    {"name": "other_rooms", "label": "Other rooms", "type": "number",
                     "width": "half"},
                ],
            },
            {
                "slug": "farm_building",
                "label": "Other Farm Building (Farm Building for Livestock)",
                "fields": [
                    *building_base(),
                    {"name": "hdr_use", "label": "Farm use", "type": "section_header",
                     "width": "full"},
                    {"name": "structure_purpose", "label": "Purpose", "type": "select",
                     "options": FARM_STRUCTURES, "width": "half"},
                    {"name": "capacity", "label": "Capacity (head or tonnes)", "type": "number",
                     "width": "half"},
                    {"name": "has_power", "label": "Three-phase power available?",
                     "type": "radio", "options": YES_NO, "width": "half"},
                    {"name": "has_water_connection", "label": "Piped water connection?",
                     "type": "radio", "options": YES_NO, "width": "half"},
                ],
            },
            {
                "slug": "aquaculture", "label": "Aquaculture / Fish Farm", "is_land": True,
                "fields": [
                    {"name": "hdr_ponds", "label": "Ponds & stock", "type": "section_header",
                     "width": "full"},
                    {"name": "pond_count", "label": "Number of Ponds", "type": "number",
                     "width": "half"},
                    {"name": "total_pond_area", "label": "Total Pond Surface (sqm)",
                     "type": "number", "width": "half", "unit": "sqm"},
                    {"name": "pond_type", "label": "Pond Construction", "type": "select",
                     "options": ["Earthen", "Lined (HDPE)", "Concrete", "Cage in lake",
                                 "Recirculating tanks"],
                     "width": "half"},
                    {"name": "species", "label": "Species Farmed", "type": "text",
                     "width": "half", "placeholder": "Tilapia, catfish…"},
                    {"name": "annual_output", "label": "Annual Output (kg)", "type": "number",
                     "width": "half", "unit": "kg"},
                    {"name": "hatchery", "label": "On-site hatchery?", "type": "radio",
                     "options": YES_NO, "width": "half"},
                    *agri_land_base(),
                    {"name": "farm_structures", "label": "Supporting Structures",
                     "type": "multiselect", "options": FARM_STRUCTURES, "width": "full"},
                ],
            },
            {
                "slug": "greenhouse", "label": "Greenhouse / Protected Cultivation",
                "fields": [
                    {"name": "hdr_house", "label": "Structure", "type": "section_header",
                     "width": "full"},
                    {"name": "greenhouse_count", "label": "Number of Units", "type": "number",
                     "width": "half"},
                    {"name": "covered_area", "label": "Total Covered Area (sqm)",
                     "type": "number", "width": "half", "unit": "sqm"},
                    {"name": "structure_material", "label": "Frame Material", "type": "select",
                     "options": ["Galvanised steel", "Timber", "Bamboo", "Aluminium"],
                     "width": "half"},
                    {"name": "cover_material", "label": "Cover Material", "type": "select",
                     "options": ["UV polythene", "Polycarbonate", "Shade net", "Glass"],
                     "width": "half"},
                    {"name": "condition", "label": "Condition", "type": "select",
                     "options": BUILDING_CONDITIONS, "width": "half"},
                    {"name": "construction_year", "label": "Year Installed", "type": "number",
                     "width": "half"},
                    {"name": "climate_control", "label": "Climate Control", "type": "multiselect",
                     "options": ["Drip fertigation", "Misting", "Ventilation fans",
                                 "Shade screens", "Heating", "None"],
                     "width": "full"},
                    {"name": "crops_grown", "label": "Crops Grown", "type": "text",
                     "width": "full"},
                    *agri_land_base(),
                ],
            },
        ],
    },
    # ============================================================ 3. RESIDENTIAL
    {
        "slug": "residential", "label": "Residential", "icon": "Home", "display_order": 3,
        "description": "Family plots, houses, condominium units and garages.",
        "subcategories": [
            {"slug": "res_plot", "label": "Land for family house", "is_land": True,
             "fields": land_infra()},
            {"slug": "condo_plot", "label": "Land for Condominium Unit", "is_land": True,
             "fields": [*land_infra(),
                        {"name": "amenities", "label": "Existing social amenities",
                         "type": "multiselect", "options": AMENITIES, "width": "full"}]},
            {"slug": "res_building", "label": "Family House",
             "fields": [
                 *building_base(),
                 {"name": "units", "label": "Number of Units that can accommodate one family",
                  "type": "number", "width": "full"},
                 {"name": "bedrooms", "label": "Bedrooms", "type": "number", "width": "half"},
                 {"name": "sitting_rooms", "label": "Sitting rooms", "type": "number",
                  "width": "half"},
                 {"name": "bathrooms", "label": "Bathrooms", "type": "number", "width": "half"},
                 {"name": "store_rooms", "label": "Store rooms", "type": "number", "width": "half"},
                 {"name": "kitchen", "label": "Kitchen", "type": "number", "width": "half"},
                 {"name": "other_rooms", "label": "Other rooms", "type": "number", "width": "half"},
             ]},
            {"slug": "condo_unit", "label": "Condominium Unit",
             "fields": [
                 {"name": "condition", "label": "Building Condition", "type": "select",
                  "options": BUILDING_CONDITIONS, "width": "half"},
                 {"name": "built_area", "label": "Built-up Area (sqm)", "type": "number",
                  "width": "half", "unit": "sqm"},
                 {"name": "floor_level", "label": "Floor on which the unit is located",
                  "type": "number", "width": "full"},
                 {"name": "hdr_accom", "label": "Accommodation of the unit",
                  "type": "section_header", "width": "full"},
                 {"name": "bedrooms", "label": "Bedrooms", "type": "number", "width": "half"},
                 {"name": "sitting_rooms", "label": "Sitting rooms", "type": "number",
                  "width": "half"},
                 {"name": "bathrooms", "label": "Bathrooms", "type": "number", "width": "half"},
                 {"name": "store_rooms", "label": "Store rooms", "type": "number", "width": "half"},
                 {"name": "kitchen", "label": "Kitchen", "type": "number", "width": "half"},
                 {"name": "other_rooms", "label": "Other rooms", "type": "number", "width": "half"},
                 {"name": "under_construction", "label": "Is this building under construction?",
                  "type": "radio", "options": YES_NO, "width": "full"},
                 {"name": "construction_year", "label": "Year of Construction", "type": "number",
                  "width": "full",
                  "conditional": {"field": "under_construction", "value": "No"}},
             ]},
            {"slug": "garage", "label": "Garage",
             "fields": [
                 {"name": "condition", "label": "Building Condition", "type": "select",
                  "options": BUILDING_CONDITIONS, "width": "half"},
                 {"name": "built_area", "label": "Built-up Area (sqm)", "type": "number",
                  "width": "half", "unit": "sqm"},
                 {"name": "wall_material", "label": "Wall Material", "type": "select",
                  "options": WALL_MATERIALS, "width": "half"},
                 {"name": "roof_material", "label": "Roof Covering Material", "type": "select",
                  "options": ROOF_COVERING, "width": "half"},
                 {"name": "floor_material", "label": "Floor Material", "type": "select",
                  "options": FLOOR_MATERIALS, "width": "half"},
                 {"name": "under_construction", "label": "Is this building under construction?",
                  "type": "radio", "options": YES_NO, "width": "full"},
                 {"name": "construction_year", "label": "Year of Construction", "type": "number",
                  "width": "full",
                  "conditional": {"field": "under_construction", "value": "No"}},
             ]},
        ],
    },
    # ============================================================ 4. COMMERCIAL
    {
        "slug": "commercial", "label": "Commercial", "icon": "Building2", "display_order": 4,
        "description": "Retail, offices, apartments, mixed-use and service stations.",
        "subcategories": [
            {"slug": "com_plot", "label": "Land for commercial plot", "is_land": True,
             "fields": land_infra()},
            {"slug": "commercial_apartment_land", "label": "Land for Apartment Building",
             "is_land": True,
             "fields": [*land_infra(),
                        {"name": "amenities", "label": "Existing social amenities",
                         "type": "multiselect", "options": AMENITIES, "width": "full"}]},
            {"slug": "office_block", "label": "Office Building",
             "fields": [
                 *building_base(),
                 {"name": "is_rented", "label": "Is this building for rent?", "type": "radio",
                  "options": YES_NO, "width": "full"},
                 {"name": "rental_area", "label": "Total Rental Area", "type": "number",
                  "width": "half", "unit": "sqm",
                  "conditional": {"field": "is_rented", "value": "Yes"}},
                 {"name": "rent_percentage", "label": "Percentage of area under rent",
                  "type": "number", "width": "half",
                  "conditional": {"field": "is_rented", "value": "Yes"}},
                 {"name": "rent_price", "label": "Rent Amount per Sqm per month",
                  "type": "number", "width": "full",
                  "conditional": {"field": "is_rented", "value": "Yes"}},
             ]},
            {"slug": "petrol_station", "label": "Petrol Station",
             "fields": [
                 {"name": "condition", "label": "Building Condition", "type": "select",
                  "options": BUILDING_CONDITIONS, "width": "full"},
                 {"name": "pumps", "label": "Type and Number of pumps", "type": "text",
                  "width": "half"},
                 {"name": "tanks", "label": "Number and capacity of underground storage tanks",
                  "type": "text", "width": "half"},
                 {"name": "is_rented", "label": "Is this petrol station under rent?",
                  "type": "radio", "options": YES_NO, "width": "full"},
                 {"name": "rent_price", "label": "Rent Price per month", "type": "number",
                  "width": "full", "conditional": {"field": "is_rented", "value": "Yes"}},
                 {"name": "under_construction", "label": "Is this building under construction?",
                  "type": "radio", "options": YES_NO, "width": "full"},
                 {"name": "construction_year", "label": "Year of Construction", "type": "number",
                  "width": "full",
                  "conditional": {"field": "under_construction", "value": "No"}},
             ]},
            {"slug": "apartment_building", "label": "Apartment",
             "fields": [
                 *building_base(),
                 {"name": "hdr_units", "label": "Number of Units", "type": "section_header",
                  "width": "full"},
                 {"name": "rooms_per_unit", "label": "Number of rooms per unit",
                  "type": "number", "width": "half"},
                 {"name": "total_units", "label": "Total number of units", "type": "number",
                  "width": "half"},
                 {"name": "floor_area_per_unit", "label": "Floor area per unit/Sqm",
                  "type": "number", "width": "half", "unit": "sqm"},
                 {"name": "units_under_rent", "label": "Number of units under rent",
                  "type": "number", "width": "half"},
                 {"name": "monthly_rent_per_unit", "label": "Monthly Rent amount per unit",
                  "type": "number", "width": "full"},
             ]},
            {"slug": "mixed_use_building", "label": "Mixed Use Building",
             "fields": [
                 *building_base(),
                 {"name": "hdr_use_types", "label": "Use Type and Area",
                  "type": "section_header", "width": "full"},
                 {"name": "residential_area", "label": "Residential Area (sqm)",
                  "type": "number", "width": "half", "unit": "sqm"},
                 {"name": "residential_rent", "label": "Residential Monthly Rent per Sqm",
                  "type": "number", "width": "half"},
                 {"name": "commercial_area", "label": "Commercial Area (sqm)", "type": "number",
                  "width": "half", "unit": "sqm"},
                 {"name": "commercial_rent", "label": "Commercial Monthly Rent per Sqm",
                  "type": "number", "width": "half"},
                 {"name": "industrial_area", "label": "Industrial Area (sqm)", "type": "number",
                  "width": "half", "unit": "sqm"},
                 {"name": "industrial_rent", "label": "Industrial Monthly Rent per Sqm",
                  "type": "number", "width": "half"},
                 {"name": "office_area", "label": "Office Area (sqm)", "type": "number",
                  "width": "half", "unit": "sqm"},
                 {"name": "office_rent", "label": "Office Monthly Rent per Sqm",
                  "type": "number", "width": "half"},
             ]},
            {"slug": "parking_building", "label": "Parking Building",
             "fields": [
                 *building_base(),
                 {"name": "car_capacity",
                  "label": "Number of cars that can park in the building",
                  "type": "number", "width": "full"},
             ]},
        ],
    },
    # ============================================================ 5. INDUSTRIAL
    {
        "slug": "industrial", "label": "Industrial", "icon": "Factory", "display_order": 5,
        "description": "Warehousing, manufacturing and serviced industrial land.",
        "subcategories": [
            {"slug": "ind_plot", "label": "Land for industrial building", "is_land": True,
             "fields": [
                 {"name": "machinery_included",
                  "label": "Is the price paid including machinery or plant equipment?",
                  "type": "radio", "options": YES_NO, "width": "full"},
                 *land_infra(),
                 {"name": "infrastructure", "label": "Other Existing Infrastructures",
                  "type": "multiselect", "options": INDUSTRIAL_INFRA, "width": "full"},
             ]},
            {"slug": "ind_building", "label": "Industrial Building",
             "fields": [
                 *building_base(),
                 {"name": "is_rented", "label": "Is this building for rent?", "type": "radio",
                  "options": YES_NO, "width": "full"},
                 {"name": "rental_area", "label": "Total Rental Area", "type": "number",
                  "width": "half", "unit": "sqm",
                  "conditional": {"field": "is_rented", "value": "Yes"}},
                 {"name": "rent_price", "label": "Rent Amount per Sqm per month",
                  "type": "number", "width": "half",
                  "conditional": {"field": "is_rented", "value": "Yes"}},
             ]},
        ],
    },
    # ============================================================ 6. PUBLIC
    {
        "slug": "public", "label": "Public", "icon": "Landmark", "display_order": 6,
        "description": "Institutional land and buildings.",
        "subcategories": [
            {"slug": "public_plot", "label": "Land for public building", "is_land": True,
             "fields": land_infra()},
            {"slug": "public_building", "label": "Public Building",
             "fields": [
                 *building_base(),
                 {"name": "is_rented", "label": "Is this building for rent?", "type": "radio",
                  "options": YES_NO, "width": "full"},
                 {"name": "rental_area", "label": "Total Rental Area", "type": "number",
                  "width": "half", "unit": "sqm",
                  "conditional": {"field": "is_rented", "value": "Yes"}},
                 {"name": "rent_price", "label": "Rent Amount per Sqm per month",
                  "type": "number", "width": "half",
                  "conditional": {"field": "is_rented", "value": "Yes"}},
             ]},
        ],
    },
]


OPTION_SETS: list[dict] = [
    {"key": "YES_NO", "label": "Yes / No", "values": YES_NO},
    {"key": "CROP_SIZES", "label": "Crop sizes", "values": CROP_SIZES},
    {"key": "COVERAGE_RATIO", "label": "Coverage ratio", "values": COVERAGE_RATIO},
    {"key": "FENCE_MATERIALS", "label": "Fence materials", "values": FENCE_MATERIALS},
    {"key": "BUILDING_CONDITIONS", "label": "Building conditions", "values": BUILDING_CONDITIONS},
    {"key": "ROOF_TYPES", "label": "Roof types", "values": ROOF_TYPES},
    {"key": "WALL_MATERIALS", "label": "Wall materials", "values": WALL_MATERIALS},
    {"key": "ROOF_COVERING", "label": "Roof covering", "values": ROOF_COVERING},
    {"key": "FLOOR_MATERIALS", "label": "Floor materials", "values": FLOOR_MATERIALS},
    {"key": "PRODUCT_TYPES", "label": "Agricultural products", "values": PRODUCT_TYPES},
    {"key": "PARKING_MATERIALS", "label": "Parking materials", "values": PARKING_MATERIALS},
    {"key": "SEWAGE_TYPES", "label": "Sewage types", "values": SEWAGE_TYPES},
    {"key": "AMENITIES", "label": "Social amenities", "values": AMENITIES},
    {"key": "INDUSTRIAL_INFRA", "label": "Industrial infrastructure", "values": INDUSTRIAL_INFRA},
    {"key": "SOIL_TYPES", "label": "Soil types", "values": SOIL_TYPES},
    {"key": "SOIL_FERTILITY", "label": "Soil fertility", "values": SOIL_FERTILITY},
    {"key": "SOIL_PH", "label": "Soil pH bands", "values": SOIL_PH},
    {"key": "TOPOGRAPHY", "label": "Topography", "values": TOPOGRAPHY},
    {"key": "EROSION_CONTROL", "label": "Erosion control", "values": EROSION_CONTROL},
    {"key": "WATER_SOURCES", "label": "Water sources", "values": WATER_SOURCES},
    {"key": "IRRIGATION_TYPES", "label": "Irrigation methods", "values": IRRIGATION_TYPES},
    {"key": "WATER_RELIABILITY", "label": "Water reliability", "values": WATER_RELIABILITY},
    {"key": "FARMING_SYSTEM", "label": "Farming systems", "values": FARMING_SYSTEM},
    {"key": "LIVESTOCK_TYPES", "label": "Livestock types", "values": LIVESTOCK_TYPES},
    {"key": "FARM_STRUCTURES", "label": "Farm structures", "values": FARM_STRUCTURES},
    {"key": "FARM_EQUIPMENT", "label": "Farm equipment", "values": FARM_EQUIPMENT},
    {"key": "CERTIFICATIONS", "label": "Agricultural certifications", "values": CERTIFICATIONS},
    {"key": "ROAD_ACCESS", "label": "Road access", "values": ROAD_ACCESS},
    {"key": "MARKET_DISTANCE", "label": "Distance to market", "values": MARKET_DISTANCE},
    {"key": "LAND_TENURE", "label": "Land tenure", "values": LAND_TENURE},
]
