"""Settings, navigation, UI strings and page copy — all admin-editable."""

SETTINGS: list[dict] = [
    # ---- brand (super admin only) ----
    {"key": "brand.name", "label": "Company name", "group": "brand", "value": "Evaramu Group Ltd",
     "value_type": "string", "is_protected": True, "display_order": 1},
    {"key": "brand.short_name", "label": "Short name", "group": "brand", "value": "Evaramu",
     "value_type": "string", "is_protected": True, "display_order": 2},
    {"key": "brand.tagline", "label": "Tagline", "group": "brand",
     "value": "We don't just sell property. We build wealth.",
     "value_type": "string", "is_protected": True, "display_order": 3},
    {"key": "brand.logo_horizontal", "label": "Horizontal logo", "group": "brand",
     "value": "/brand/logo-horizontal.png", "value_type": "image", "is_protected": True,
     "display_order": 4},
    {"key": "brand.logo_mark", "label": "Logo mark (light backgrounds)", "group": "brand",
     "value": "/brand/logo-mark.png", "value_type": "image", "is_protected": True,
     "display_order": 5},
    {"key": "brand.logo_mark_light", "label": "Logo mark (dark backgrounds)", "group": "brand",
     "value": "/brand/logo-mark-light.png", "value_type": "image", "is_protected": True,
     "display_order": 6},
    {"key": "brand.favicon", "label": "Favicon", "group": "brand", "value": "/favicon.png",
     "value_type": "image", "is_protected": True, "display_order": 7},

    # ---- theme (super admin only) ----
    {"key": "theme.navy", "label": "Primary navy", "group": "theme", "value": "#062b4f",
     "value_type": "color", "is_protected": True, "display_order": 1,
     "description": "Sampled from the corporate logo. Drives every surface and text token."},
    {"key": "theme.gold", "label": "Accent gold", "group": "theme", "value": "#be7c28",
     "value_type": "color", "is_protected": True, "display_order": 2},
    {"key": "theme.sand", "label": "Warm neutral", "group": "theme", "value": "#fbfaf8",
     "value_type": "color", "is_protected": True, "display_order": 3},
    {"key": "theme.default_mode", "label": "Default colour mode", "group": "theme",
     "value": "system", "value_type": "string", "is_protected": True, "display_order": 4,
     "description": "light | dark | system"},
    {"key": "theme.font_display", "label": "Display typeface", "group": "theme",
     "value": "Fraunces", "value_type": "string", "is_protected": True, "display_order": 5},
    {"key": "theme.font_sans", "label": "Body typeface", "group": "theme",
     "value": "Plus Jakarta Sans", "value_type": "string", "is_protected": True,
     "display_order": 6},

    # ---- contact ----
    {"key": "contact.email", "label": "Public email", "group": "contact",
     "value": "hello@evaramu.rw", "value_type": "email", "display_order": 1},
    {"key": "contact.phone", "label": "Phone", "group": "contact", "value": "+250 792 879 777",
     "value_type": "string", "display_order": 2},
    {"key": "contact.whatsapp", "label": "WhatsApp number", "group": "contact",
     "value": "250792879777", "value_type": "string", "display_order": 3},
    {"key": "contact.momo_code", "label": "MoMo Pay code", "group": "contact",
     "description": "Shown so clients pay the company account rather than an individual number.",
     "value": "70702", "value_type": "string", "display_order": 4},
    {"key": "contact.address", "label": "Office address", "group": "contact",
     "value": "KG 11 Ave, Kimihurura, Gasabo District, Kigali, Rwanda",
     "value_type": "text", "display_order": 5},
    {"key": "contact.hours", "label": "Weekday hours", "group": "contact",
     "value": "Monday – Friday · 08:00 – 18:00", "value_type": "string", "display_order": 6},
    {"key": "contact.hours_saturday", "label": "Saturday hours", "group": "contact",
     "value": "Saturday · 09:00 – 14:00", "value_type": "string", "display_order": 7},
    {"key": "contact.latitude", "label": "Office latitude", "group": "contact",
     "value": "-1.9441", "value_type": "number", "display_order": 8},
    {"key": "contact.longitude", "label": "Office longitude", "group": "contact",
     "value": "30.0619", "value_type": "number", "display_order": 9},

    # ---- social ----
    {"key": "social.instagram", "label": "Instagram", "group": "social",
     "value": "https://instagram.com/evaramu_group", "value_type": "url", "display_order": 1},
    {"key": "social.facebook", "label": "Facebook", "group": "social",
     "value": "https://facebook.com/evaramu_group", "value_type": "url", "display_order": 2},
    {"key": "social.linkedin", "label": "LinkedIn", "group": "social",
     "value": "https://linkedin.com/company/evaramu_group", "value_type": "url",
     "display_order": 3},
    {"key": "social.youtube", "label": "YouTube", "group": "social",
     "value": "https://youtube.com/@evaramu_group", "value_type": "url", "display_order": 4},
    {"key": "social.handle", "label": "Handle", "group": "social", "value": "@evaramu_group",
     "value_type": "string", "display_order": 5},

    # ---- seo ----
    {"key": "seo.site_url", "label": "Canonical site URL", "group": "seo",
     "value": "https://evaramu.rw", "value_type": "url", "display_order": 1},
    {"key": "seo.default_title", "label": "Default page title", "group": "seo",
     "value": "Evaramu Group Ltd — Real Estate, Construction & Property Wealth in Kigali",
     "value_type": "string", "display_order": 2},
    {"key": "seo.default_description", "label": "Default meta description", "group": "seo",
     "value": ("Buy verified land and property in Rwanda, build with our construction "
               "division, earn rental income and grow from one property to a portfolio."),
     "value_type": "text", "display_order": 3},
    {"key": "seo.og_image", "label": "Default share image", "group": "seo",
     "value": "/brand/logo-horizontal.png", "value_type": "image", "display_order": 4},

    # ---- features (super admin only) ----
    {"key": "features.captcha_enabled", "label": "Require captcha on public forms",
     "group": "features", "value": "true", "value_type": "boolean", "is_protected": True,
     "display_order": 1},
    {"key": "features.registration_open", "label": "Allow public registration",
     "group": "features", "value": "true", "value_type": "boolean", "is_protected": True,
     "display_order": 2},
    {"key": "features.default_locale", "label": "Default language", "group": "features",
     "value": "en", "value_type": "string", "display_order": 3},
    {"key": "features.locales", "label": "Enabled languages", "group": "features",
     "value": "en,rw,fr", "value_type": "string", "display_order": 4},
    {"key": "features.vr_enabled", "label": "Show VR / 360 tours", "group": "features",
     "value": "true", "value_type": "boolean", "display_order": 5},

    # ---- marketplace ----
    {"key": "marketplace.price_max", "label": "Price filter ceiling (RWF)",
     "description": "Upper bound of the marketplace price slider. Above it, the filter reads 'Any'.",
     "group": "marketplace", "value": "600000000", "value_type": "number", "display_order": 1},
    {"key": "marketplace.per_page", "label": "Listings per page",
     "description": "How many cards load before 'Show more'.",
     "group": "marketplace", "value": "9", "value_type": "number", "display_order": 2},

    # ---- company ----
    {"key": "company.rdb", "label": "Registration line", "group": "company",
     "value": "Registered with the Rwanda Development Board (RDB)", "value_type": "string",
     "display_order": 1},
    {"key": "company.founded", "label": "Founded", "group": "company", "value": "2025",
     "value_type": "string", "display_order": 2},
    {"key": "company.description", "label": "Company description", "group": "company",
     "value": ("Evaramu Group Ltd is a full-cycle real estate, construction and property "
               "wealth company in Kigali, Rwanda."),
     "value_type": "text", "display_order": 3},
]


NAVIGATION: list[dict] = [
    {"menu": "header", "label": "Home", "translation_key": "nav.home", "href": "/", "order": 1},
    {"menu": "header", "label": "Properties", "translation_key": "nav.properties",
     "href": "/properties", "order": 2, "children": [
         {"label": "Browse all properties", "href": "/properties", "icon": "LayoutGrid",
          "description": "Verified land, homes and commercial space across Rwanda"},
         {"label": "Land & plots", "href": "/properties?category=residential",
          "icon": "MapPinned", "description": "Residential and commercial plots in growth corridors"},
         {"label": "Houses & apartments", "href": "/properties?category=commercial",
          "icon": "Home", "description": "Family houses, condominium units and apartments"},
         {"label": "Farms & agricultural land", "href": "/properties?category=agricultural",
          "icon": "Tractor", "description": "Cropland, plantations, livestock and aquaculture"},
         {"label": "Sell or list a property", "href": "/sell", "icon": "Upload",
          "description": "List with the agency in a guided, documented process"},
     ]},
    {"menu": "header", "label": "Services", "translation_key": "nav.services",
     "href": "/services", "order": 3, "children": [
         {"label": "The Wealth Cycle", "href": "/wealth-cycle", "icon": "RefreshCw",
          "description": "Buy → build → earn → sell → reinvest. Our signature model"},
         {"label": "Construction & renovation", "href": "/construction", "icon": "HardHat",
          "description": "Standard, Premium and Luxury finishing packages"},
         {"label": "Property management", "href": "/services#management", "icon": "KeyRound",
          "description": "Tenants, maintenance, rent collection, monthly reporting"},
         {"label": "Diaspora services", "href": "/services#diaspora", "icon": "Globe2",
          "description": "Buy and build from abroad with verified remote reporting"},
     ]},
    {"menu": "header", "label": "Our Team", "translation_key": "nav.team", "href": "/team",
     "order": 4},
    {"menu": "header", "label": "Join Us", "translation_key": "nav.join", "href": "/join",
     "order": 5},
    {"menu": "header", "label": "About", "translation_key": "nav.about", "href": "/about",
     "order": 6},
    {"menu": "header", "label": "Insights", "translation_key": "nav.insights",
     "href": "/insights", "order": 7},
    {"menu": "header", "label": "Contact", "translation_key": "nav.contact", "href": "/contact",
     "order": 8},

    {"menu": "footer_properties", "label": "All listings", "href": "/properties", "order": 1},
    {"menu": "footer_properties", "label": "Land & plots",
     "href": "/properties?category=residential", "order": 2},
    {"menu": "footer_properties", "label": "Farms & agricultural land",
     "href": "/properties?category=agricultural", "order": 3},
    {"menu": "footer_properties", "label": "Sell your property", "href": "/sell", "order": 4},

    {"menu": "footer_services", "label": "The Wealth Cycle", "href": "/wealth-cycle", "order": 1},
    {"menu": "footer_services", "label": "Construction & renovation", "href": "/construction",
     "order": 2},
    {"menu": "footer_services", "label": "Property management", "href": "/services#management",
     "order": 3},
    {"menu": "footer_services", "label": "Book a consultation", "href": "/consultation",
     "order": 4},

    {"menu": "footer_company", "label": "About Evaramu", "href": "/about", "order": 1},
    {"menu": "footer_company", "label": "Our team", "href": "/team", "order": 2},
    {"menu": "footer_company", "label": "Join our agency", "href": "/join", "order": 3},
    {"menu": "footer_company", "label": "Contact us", "href": "/contact", "order": 4},
]


MARKET_STATS: list[dict] = [
    {"key": "housing_deficit", "value": "400,000+", "label": "National housing deficit",
     "detail": "Units short, and the gap widens every year", "icon": "Home", "display_order": 1,
     "source": "Rwanda housing market analysis 2025"},
    {"key": "land_appreciation", "value": "15–20%", "label": "Annual land appreciation",
     "detail": "In strategic Kigali growth corridors", "icon": "TrendingUp", "display_order": 2},
    {"key": "rental_yield", "value": "8–12%", "label": "Prime rental yield",
     "detail": "Apartments per year · 7–10% on villas", "icon": "Wallet", "display_order": 3},
    {"key": "kigali_demand", "value": "2×", "label": "Kigali demand by 2032",
     "detail": "367,000 → 721,000 households", "icon": "Users", "display_order": 4},
]


WEALTH_CYCLE: list[dict] = [
    {"step": 1, "title": "Find", "icon": "Search",
     "action": "We source verified land or property matching your budget and goals.",
     "outcome": "You buy your first property with full guidance."},
    {"step": 2, "title": "Build / Improve", "icon": "HardHat",
     "action": "We renovate, finish or construct to increase the value.",
     "outcome": "Property value increases 20–50%."},
    {"step": 3, "title": "Earn", "icon": "Wallet",
     "action": "We place tenants and manage the property for passive income.",
     "outcome": "Monthly rental income starts flowing."},
    {"step": 4, "title": "Sell at Peak", "icon": "TrendingUp",
     "action": "We advise on the right time to sell and market it professionally.",
     "outcome": "You capture appreciation plus the rental gains."},
    {"step": 5, "title": "Reinvest", "icon": "RefreshCw",
     "action": "We redirect the proceeds into 2–3 new properties.",
     "outcome": "You now own multiple assets. The cycle repeats."},
    {"step": 6, "title": "Repeat", "icon": "Layers",
     "action": "The cycle continues with a larger portfolio each round.",
     "outcome": "From 1 property to 4–5 within 3 years."},
]


SERVICE_LINES: list[dict] = [
    {"slug": "buy", "title": "Buy land & property", "division": "Realty", "icon": "Search",
     "tagline": "Verified before it reaches you", "href": "/properties", "display_order": 1,
     "description": ("Every parcel we list is checked at the National Land Authority before it "
                     "appears on the platform."),
     "bullets": ["Title verified at NLA before listing",
                 "UPI, parcel size and GIS coordinates published",
                 "Negotiation handled by your assigned consultant",
                 "Digital contract, receipts and transfer support"]},
    {"slug": "sell", "title": "Sell or list your property", "division": "Realty", "icon": "Upload",
     "tagline": "Marketed properly, sold faster", "href": "/sell", "display_order": 2,
     "description": "Drone video, professional photography and a mapped online listing.",
     "bullets": ["Free valuation and pricing strategy",
                 "Drone video and professional photography",
                 "Buyer qualification before every viewing",
                 "Commission agreed in writing up front"]},
    {"slug": "build", "title": "Construction & renovation", "division": "Construction",
     "icon": "HardHat", "tagline": "One company brokers and builds", "href": "/construction",
     "display_order": 3,
     "description": "Fixed-price contracts, a 15% contingency buffer and weekly cost tracking.",
     "bullets": ["Fixed-price client contracts", "Weekly cost tracking and photo reports",
                 "Vetted masons, electricians, plumbers and tilers",
                 "Remote supervision available for diaspora clients"]},
    {"slug": "manage", "title": "Property management", "division": "Realty", "icon": "KeyRound",
     "tagline": "Passive income, actively protected", "href": "/services#management",
     "display_order": 4,
     "description": "We place tenants, collect rent, handle maintenance and report monthly.",
     "bullets": ["Tenant sourcing and screening", "Rent collection and arrears follow-up",
                 "Maintenance coordination and inspections",
                 "Monthly statement to your inbox"]},
    {"slug": "diaspora", "title": "Diaspora services", "division": "Group", "icon": "Globe2",
     "tagline": "Invest home without flying home", "href": "/services#diaspora",
     "display_order": 5,
     "description": "Video updates, verified titles, digital contracts and monthly reporting.",
     "bullets": ["Video walkthroughs of every shortlisted property",
                 "Independent title verification before deposit",
                 "Digital contracts signed from anywhere",
                 "Monthly build diary and photo reporting"]},
    {"slug": "wealth", "title": "The Wealth Cycle", "division": "Group", "icon": "RefreshCw",
     "tagline": "From one property to a portfolio", "href": "/wealth-cycle", "display_order": 6,
     "description": "We stay with you through buy, build, earn, sell and reinvest.",
     "bullets": ["Portfolio plan built around your budget",
                 "Timing advice on when to sell, not just what to buy",
                 "Proceeds redirected into 2–3 new assets",
                 "Ongoing management as the portfolio grows"]},

    # ---- land services: the paperwork that has to exist before a build ----
    {"slug": "survey", "title": "Plot survey & boundary beacons", "division": "Construction",
     "icon": "MapPinned", "tagline": "Gutera bornes — your corners, marked and recorded",
     "href": "/services#land", "display_order": 7,
     "description": ("A licensed surveyor measures the parcel and plants the boundary beacons, "
                     "so the corners on the ground match the corners on the title."),
     "bullets": ["Licensed land surveyor on site",
                 "Boundary beacons (bornes) planted at every corner",
                 "Measurements reconciled against the cadastre",
                 "Neighbour boundary disputes flagged before you build"]},

    {"slug": "gps-check", "title": "GPS & parcel verification", "division": "Construction",
     "icon": "Compass", "tagline": "Confirm the plot you were shown is the plot on the title",
     "href": "/services#land", "display_order": 8,
     "description": ("We take GPS readings on the ground and check them against the parcel "
                     "registered under that UPI at the National Land Authority."),
     "bullets": ["GPS coordinates captured on site",
                 "Checked against the registered parcel geometry",
                 "Size and shape confirmed against the title",
                 "Written report you can act on"]},

    {"slug": "cadastral-plan", "title": "Cadastral plan (fiche cadastrale)", "division": "Construction",
     "icon": "FileText", "tagline": "The parcel plan your architect will ask for",
     "href": "/services#land", "display_order": 9,
     "description": ("We request the fiche cadastrale for your parcel from the National Land "
                     "Authority and hand it over with the title search."),
     "bullets": ["Fiche cadastrale requested on your behalf",
                 "Land title search run at the same time",
                 "Certified copies for your architect and the district",
                 "Diaspora clients handled entirely remotely"]},

    {"slug": "building-permit", "title": "Building permit support", "division": "Construction",
     "icon": "FileSignature", "tagline": "Uruhushya rwo kubaka — legally cleared to build",
     "href": "/services#land", "display_order": 10,
     "description": ("Drawings, structural certification and the district submission — we "
                     "assemble the file and follow it through the One Stop Centre until the "
                     "permit is issued."),
     "bullets": ["Architectural and structural drawings prepared",
                 "Zoning and land-use compliance checked first",
                 "Submitted through the District One Stop Centre",
                 "Followed up until the permit is in your hand"]},
]


CONSTRUCTION_PACKAGES: list[dict] = [
    {"slug": "standard", "name": "Standard", "tier": "Standard",
     "tagline": "One family, built properly",
     "suited_to": "A single-family home — one household, one kitchen, one entrance.",
     "price_per_sqm": 320000, "show_price": False,
     "price_note": "Quoted after the site visit — see why below",
     "duration": "3–5 months", "is_popular": False, "display_order": 1,
     "description": ("The house most families in Rwanda are actually building: three or four "
                     "bedrooms, a sitting room, a kitchen and the wet areas, on one plot for "
                     "one household."),
     "includes": ["Fixed-price contract with 15% contingency stated up front",
                  "Dedicated site supervisor on every visit",
                  "Weekly photo report and running cost sheet",
                  "Vetted sub-contractors only — no casual labour",
                  "12-month workmanship warranty"],
     "finishes": [{"label": "Layout", "value": "Single household, 3–4 bedrooms"},
                  {"label": "Walls", "value": "Cement blocks, plastered and painted"},
                  {"label": "Roof", "value": "Corrugated iron sheets on treated timber"},
                  {"label": "Floors", "value": "Sand cement screed with ceramic tiles in wet areas"},
                  {"label": "Windows", "value": "Powder-coated aluminium, clear glazing"},
                  {"label": "Fittings", "value": "Standard-grade sanitary ware and switchgear"}]},

    {"slug": "premium", "name": "Premium", "tier": "Premium",
     "tagline": "Two households, or a family that is still growing",
     "suited_to": ("A two-in-one or multi-unit house — separate entrances and services for "
                   "two or more households under one roof."),
     "price_per_sqm": 520000, "show_price": False,
     "price_note": "Quoted after the site visit — see why below",
     "duration": "5–8 months", "is_popular": True, "display_order": 2,
     "description": ("Built for how families here actually live and earn: two or more self-"
                     "contained units in one structure. Live in one, let the other, or keep it "
                     "for the children — which is what makes this the package most Wealth Cycle "
                     "builds use."),
     "includes": ["Everything in Standard",
                  "Separate entrance, kitchen and meter per unit",
                  "Architectural drawings and structural certification",
                  "Full tiling, ceiling and joinery package",
                  "Landscaping and boundary wall included",
                  "Quantity surveyor cost review at each milestone",
                  "24-month workmanship warranty"],
     "finishes": [{"label": "Layout", "value": "Two or more self-contained units"},
                  {"label": "Services", "value": "Independent water and power metering per unit"},
                  {"label": "Walls", "value": "Clay burnt brick or reinforced concrete, skim finish"},
                  {"label": "Roof", "value": "Tiled double-pitch on engineered trusses"},
                  {"label": "Floors", "value": "Large-format porcelain tiles throughout"},
                  {"label": "Windows", "value": "Thermally broken aluminium, tinted glazing"},
                  {"label": "Fittings", "value": "Imported sanitary ware, branded switchgear"}]},

    {"slug": "luxury", "name": "Luxury", "tier": "Luxury",
     "tagline": "Standalone villas and mansions",
     "suited_to": "An architect-designed standalone house on a plot that carries it.",
     "price_per_sqm": 850000, "show_price": False,
     "price_note": "Quoted after the site visit — see why below",
     "duration": "8–14 months", "is_popular": False, "display_order": 3,
     "description": ("Architect-led houses on the ridges and headline addresses — designed one "
                     "at a time, not chosen from a catalogue."),
     "includes": ["Everything in Premium",
                  "Named architect and interior designer on the project",
                  "3D visualisation and material sample board before build",
                  "Smart home wiring, solar and backup power provision",
                  "Pool, garden design and outdoor lighting",
                  "36-month workmanship warranty"],
     "finishes": [{"label": "Layout", "value": "Standalone villa or mansion, architect-designed"},
                  {"label": "Walls", "value": "Reinforced concrete frame, natural stone accents"},
                  {"label": "Roof", "value": "Concrete flat roof or specified architectural tile"},
                  {"label": "Floors", "value": "Engineered hardwood and stone"},
                  {"label": "Windows", "value": "Full-height glazing systems, sliding stacks"},
                  {"label": "Fittings", "value": "Designer specification throughout"}]},
]


CONSULTATION_TYPES: list[dict] = [
    {"slug": "discovery", "title": "Free discovery call", "duration_minutes": 30,
     "price_label": "Free", "icon": "Phone", "display_order": 1,
     "modes": ["Phone", "WhatsApp video", "Google Meet"], "available_days": [1, 2, 3, 4, 5],
     "slots": ["08:30", "09:30", "10:30", "11:30", "14:00", "15:00", "16:00", "17:00"],
     "description": ("Tell us your budget and what you are trying to achieve. We will tell you "
                     "honestly whether we can help and what it would cost.")},
    {"slug": "viewing", "title": "Property viewing", "duration_minutes": 90, "price_label": "Free",
     "icon": "MapPinned", "display_order": 2,
     "modes": ["On site", "Live video walkthrough"], "available_days": [1, 2, 3, 4, 5, 6],
     "slots": ["09:00", "11:00", "14:00", "16:00"],
     "description": ("Walk a shortlisted property with your consultant. Diaspora clients get "
                     "the same viewing as a live video call with the UPI on screen.")},
    {"slug": "wealth-plan", "title": "Wealth Cycle planning session", "duration_minutes": 60,
     "price_label": "Free for clients", "icon": "RefreshCw", "display_order": 3,
     "modes": ["Office", "Google Meet"], "available_days": [1, 2, 3, 4, 5],
     "slots": ["09:00", "10:30", "14:00", "15:30"],
     "description": "We map your capital against a three-year portfolio plan."},
    {"slug": "construction", "title": "Construction consultation", "duration_minutes": 60,
     "price_label": "RWF 25,000 — credited to your build", "icon": "HardHat", "display_order": 4,
     "modes": ["On site", "Office"], "available_days": [2, 3, 4, 6],
     "slots": ["08:00", "10:00", "13:00", "15:00"],
     "description": "Bring your plot or your drawings for an indicative price per square metre."},
    {"slug": "diaspora", "title": "Diaspora investment briefing", "duration_minutes": 45,
     "price_label": "Free", "icon": "Globe2", "display_order": 5,
     "modes": ["Google Meet", "Zoom"], "available_days": [1, 3, 5, 6],
     "slots": ["07:00", "08:00", "17:00", "18:00", "19:00", "20:00"],
     "description": "Scheduled across time zones. Title verification, remote payment, transfer."},
    {"slug": "valuation", "title": "Seller valuation visit", "duration_minutes": 60,
     "price_label": "Free", "icon": "Calculator", "display_order": 6,
     "modes": ["On site"], "available_days": [1, 2, 3, 4, 5],
     "slots": ["09:00", "11:00", "14:00", "16:00"],
     "description": "We assess your property against recent comparable sales in the sector."},
]


DISTRICTS: list[dict] = [
    {"name": "Gasabo", "province": "Kigali City", "display_order": 1},
    {"name": "Kicukiro", "province": "Kigali City", "display_order": 2},
    {"name": "Nyarugenge", "province": "Kigali City", "display_order": 3},
    {"name": "Bugesera", "province": "Eastern Province", "display_order": 4},
    {"name": "Rwamagana", "province": "Eastern Province", "display_order": 5},
    {"name": "Kayonza", "province": "Eastern Province", "display_order": 6},
    {"name": "Musanze", "province": "Northern Province", "display_order": 7},
    {"name": "Rulindo", "province": "Northern Province", "display_order": 8},
    {"name": "Huye", "province": "Southern Province", "display_order": 9},
    {"name": "Muhanga", "province": "Southern Province", "display_order": 10},
    {"name": "Rubavu", "province": "Western Province", "display_order": 11},
    {"name": "Karongi", "province": "Western Province", "display_order": 12},
]
