import { useCallback, useEffect, useState } from 'react'
import { RefreshCw } from 'lucide-react'
import { useT } from '@/lib/i18n'
import { api } from '@/lib/api'

/** The server binds each challenge to the endpoint that will consume it. */
export type CaptchaScope =
  | 'login'
  | 'register'
  | 'booking'
  | 'listing'
  | 'enquiry'
  | 'contact'
  | 'application'

export interface CaptchaValue {
  captcha_token: string
  captcha_answer: string
}

interface Challenge {
  token: string
  prompt: string
  image_svg: string
  expires_in: number
}

/**
 * Our own challenge rather than a third-party widget: it costs one encrypted
 * round-trip, loads no external script, and keeps the whole exchange inside
 * the sealed channel. Scrapers have to solve a distorted SVG they cannot read
 * from the DOM as text.
 */
export function Captcha({
  value,
  onChange,
  scope,
  compact = false,
}: {
  value: CaptchaValue
  onChange: (next: CaptchaValue) => void
  /** Must match the scope the endpoint verifies against, or the answer is rejected. */
  scope: CaptchaScope
  compact?: boolean
}) {
  const t = useT()
  const [challenge, setChallenge] = useState<Challenge | null>(null)
  const [loading, setLoading] = useState(false)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const next = await api.get<Challenge>(`/auth/captcha?scope=${scope}`)
      setChallenge(next)
      onChange({ captcha_token: next.token, captcha_answer: '' })
    } catch {
      setChallenge(null)
    } finally {
      setLoading(false)
    }
    // `onChange` is re-created every render by most callers; depending on it
    // would refetch the challenge on every keystroke.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [scope])

  useEffect(() => {
    void load()
  }, [load])

  if (!challenge) {
    return (
      <div className="h-16 animate-pulse rounded-2xl border border-line bg-canvas-alt" aria-hidden />
    )
  }

  return (
    <div className={compact ? 'space-y-2' : 'space-y-2.5'}>
      <label
        htmlFor={`captcha-${challenge.token.slice(0, 6)}`}
        className="block text-[0.8125rem] font-medium text-ink-soft"
      >
        {challenge.prompt}
      </label>

      <div className="flex items-center gap-3">
        <div
          className="shrink-0 overflow-hidden rounded-xl border border-line"
          // The SVG is generated by our own API inside the encrypted channel.
          dangerouslySetInnerHTML={{ __html: challenge.image_svg }}
        />

        <button
          type="button"
          onClick={() => void load()}
          disabled={loading}
          aria-label={t('ui.newChallenge')}
          className="grid size-9 shrink-0 place-items-center rounded-full border border-line text-ink-soft transition-colors hover:border-line-strong hover:text-ink disabled:opacity-50"
        >
          <RefreshCw className={loading ? 'size-4 animate-spin' : 'size-4'} strokeWidth={2.2} />
        </button>
      </div>

      <input
        id={`captcha-${challenge.token.slice(0, 6)}`}
        required
        autoComplete="off"
        value={value.captcha_answer}
        onChange={(e) => onChange({ captcha_token: challenge.token, captcha_answer: e.target.value })}
        placeholder={t('ui.yourAnswer')}
        className="h-11 w-full rounded-2xl border border-line bg-canvas px-4 text-[0.9375rem] text-ink transition-colors placeholder:text-ink-faint focus:border-gold-500 focus:bg-surface focus:outline-none"
      />
    </div>
  )
}

export const EMPTY_CAPTCHA: CaptchaValue = { captcha_token: '', captcha_answer: '' }
